/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

/**
 *
 * @author Apotheas
 */
public class JPanelFormOrders extends javax.swing.JPanel {

    /**
     * Creates new form JPanelOrders
     */
    public JPanelFormOrders() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneOrders = new javax.swing.JTabbedPane();
        jPanelManage = new javax.swing.JPanel();
        jPanelSearchOrder = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jLabelOrderStatus = new javax.swing.JLabel();
        jComboBoxOrderStatus = new javax.swing.JComboBox<>();
        jButtonSearch = new javax.swing.JButton();
        jPanelCart = new javax.swing.JPanel();
        jScrollPaneCart = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButtonSetStatus = new javax.swing.JButton();
        jPanelOrdersWaiting = new javax.swing.JPanel();
        jScrollPaneOrdersWaiting = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanelNew = new javax.swing.JPanel();
        jPanelCartN = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabelAddBook = new javax.swing.JLabel();
        jTextAddBook = new javax.swing.JTextField();
        jButtonAddBook = new javax.swing.JButton();
        jLabelQuantity = new javax.swing.JLabel();
        jTextQuantity = new javax.swing.JTextField();
        jButtonDeleteLine = new javax.swing.JButton();
        jButtonClearCart = new javax.swing.JButton();
        jPanelShipping = new javax.swing.JPanel();
        jLabelLastNameShipp = new javax.swing.JLabel();
        jTextLastNameShipp = new javax.swing.JTextField();
        jLabelFirstNameShipp = new javax.swing.JLabel();
        jTextFirstNameShipp = new javax.swing.JTextField();
        jLabelStreetShipp = new javax.swing.JLabel();
        jLabelZipShipp = new javax.swing.JLabel();
        jLabelCityShipp = new javax.swing.JLabel();
        jTextStreetShipp = new javax.swing.JTextField();
        jTextCityShipp = new javax.swing.JTextField();
        jTextZipShipp = new javax.swing.JTextField();
        jPanelBilling = new javax.swing.JPanel();
        jRadioButtonSame = new javax.swing.JRadioButton();
        jLabelZipBill = new javax.swing.JLabel();
        jTextCityBill = new javax.swing.JTextField();
        jLabelLastNameBill = new javax.swing.JLabel();
        jTextFirstNameBill = new javax.swing.JTextField();
        jTextLastNameBill = new javax.swing.JTextField();
        jTextZipBill = new javax.swing.JTextField();
        jLabelStreetBill = new javax.swing.JLabel();
        jLabelFirstNameBill = new javax.swing.JLabel();
        jTextStreetBill = new javax.swing.JTextField();
        jLabelCityBill = new javax.swing.JLabel();
        jPanelCheckout = new javax.swing.JPanel();
        jButtonProceed = new javax.swing.JButton();
        jLabelHolderName = new javax.swing.JLabel();
        jTextHolderName = new javax.swing.JTextField();
        jLabelCard = new javax.swing.JLabel();
        jLabelExpDate = new javax.swing.JLabel();
        jLabelCCV = new javax.swing.JLabel();
        jTextCard = new javax.swing.JTextField();
        jTextExpDate = new javax.swing.JTextField();
        jTextCCV = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelTotalView = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanelSearchOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Search order"));

        jLabelSearch.setText("Order id / User  : ");

        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });

        jLabelOrderStatus.setText("Order Status  :");

        jComboBoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shipped", "Item 2", "Item 3", "Item 4" }));

        jButtonSearch.setText("Search");

        jPanelCart.setBorder(javax.swing.BorderFactory.createTitledBorder("Shopping Cart"));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Title", "Author", "Quantity"
            }
        ));
        jScrollPaneCart.setViewportView(jTable5);

        javax.swing.GroupLayout jPanelCartLayout = new javax.swing.GroupLayout(jPanelCart);
        jPanelCart.setLayout(jPanelCartLayout);
        jPanelCartLayout.setHorizontalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        jPanelCartLayout.setVerticalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        jButtonSetStatus.setText("Set");

        javax.swing.GroupLayout jPanelSearchOrderLayout = new javax.swing.GroupLayout(jPanelSearchOrder);
        jPanelSearchOrder.setLayout(jPanelSearchOrderLayout);
        jPanelSearchOrderLayout.setHorizontalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelSearch)
                .addGap(18, 18, 18)
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelOrderStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSetStatus)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSearchOrderLayout.setVerticalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderStatus)
                    .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonSetStatus))
                .addGap(18, 18, 18)
                .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanelOrdersWaiting.setBorder(javax.swing.BorderFactory.createTitledBorder("Orders waiting for Traitment"));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID ", "User", "Adresse", "Date"
            }
        ));
        jScrollPaneOrdersWaiting.setViewportView(jTable6);

        javax.swing.GroupLayout jPanelOrdersWaitingLayout = new javax.swing.GroupLayout(jPanelOrdersWaiting);
        jPanelOrdersWaiting.setLayout(jPanelOrdersWaitingLayout);
        jPanelOrdersWaitingLayout.setHorizontalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting)
                .addContainerGap())
        );
        jPanelOrdersWaitingLayout.setVerticalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelManageLayout = new javax.swing.GroupLayout(jPanelManage);
        jPanelManage.setLayout(jPanelManageLayout);
        jPanelManageLayout.setHorizontalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelManageLayout.setVerticalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("Manage", jPanelManage);

        jPanelNew.setBorder(javax.swing.BorderFactory.createTitledBorder("New Order"));

        jPanelCartN.setBorder(javax.swing.BorderFactory.createTitledBorder("Shopping Cart"));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title", "Author", "Quantity", "Cost"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jPanelCartNLayout = new javax.swing.GroupLayout(jPanelCartN);
        jPanelCartN.setLayout(jPanelCartNLayout);
        jPanelCartNLayout.setHorizontalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanelCartNLayout.setVerticalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabelAddBook.setText("Isbn/Title  : ");

        jButtonAddBook.setText("Add");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jLabelQuantity.setText("Quantity  :");

        jButtonDeleteLine.setText("Delete");

        jButtonClearCart.setText("Clear");

        jPanelShipping.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Adress"));

        jLabelLastNameShipp.setText("Last Name  :");

        jLabelFirstNameShipp.setText("First Name  :");

        jLabelStreetShipp.setText("Street   :");

        jLabelZipShipp.setText("Zip Code  :");

        jLabelCityShipp.setText("City  :");

        jTextZipShipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipShippActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShippingLayout = new javax.swing.GroupLayout(jPanelShipping);
        jPanelShipping.setLayout(jPanelShippingLayout);
        jPanelShippingLayout.setHorizontalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelFirstNameShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFirstNameShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelCityShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelZipShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelStreetShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelLastNameShipp)
                        .addGap(12, 12, 12)
                        .addComponent(jTextLastNameShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelShippingLayout.setVerticalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstNameShipp)
                    .addComponent(jTextFirstNameShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastNameShipp)
                    .addComponent(jTextLastNameShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetShipp)
                    .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelZipShipp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jTextZipShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCityShipp))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelBilling.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing Adress"));

        jRadioButtonSame.setText("Same as Shipping");

        jLabelZipBill.setText("Zip Code  :");

        jLabelLastNameBill.setText("Last Name  :");

        jTextZipBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipBillActionPerformed(evt);
            }
        });

        jLabelStreetBill.setText("Street   :");

        jLabelFirstNameBill.setText("First Name  :");

        jLabelCityBill.setText("City  :");

        javax.swing.GroupLayout jPanelBillingLayout = new javax.swing.GroupLayout(jPanelBilling);
        jPanelBilling.setLayout(jPanelBillingLayout);
        jPanelBillingLayout.setHorizontalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSame)
                    .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelBillingLayout.createSequentialGroup()
                            .addComponent(jLabelFirstNameBill)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFirstNameBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBillingLayout.createSequentialGroup()
                            .addComponent(jLabelCityBill)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBillingLayout.createSequentialGroup()
                            .addComponent(jLabelZipBill)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextZipBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBillingLayout.createSequentialGroup()
                            .addComponent(jLabelStreetBill)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelBillingLayout.createSequentialGroup()
                            .addComponent(jLabelLastNameBill)
                            .addGap(12, 12, 12)
                            .addComponent(jTextLastNameBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelBillingLayout.setVerticalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addComponent(jRadioButtonSame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstNameBill)
                    .addComponent(jTextFirstNameBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastNameBill)
                    .addComponent(jTextLastNameBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetBill)
                    .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZipBill)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jTextZipBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCityBill))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCheckout.setBorder(javax.swing.BorderFactory.createTitledBorder("Checkout"));

        jButtonProceed.setText("Proceed");

        jLabelHolderName.setText("Holder name  :");

        jLabelCard.setText("Card number  :");

        jLabelExpDate.setText("Exp Date  :");

        jLabelCCV.setText("CCV  :");

        jLabelTotal.setText("Total  TTC  :");

        jLabelTotalView.setText("99.99 €");

        javax.swing.GroupLayout jPanelCheckoutLayout = new javax.swing.GroupLayout(jPanelCheckout);
        jPanelCheckout.setLayout(jPanelCheckoutLayout);
        jPanelCheckoutLayout.setHorizontalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckoutLayout.createSequentialGroup()
                                .addComponent(jLabelHolderName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextHolderName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckoutLayout.createSequentialGroup()
                                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCard)
                                    .addComponent(jLabelExpDate)
                                    .addComponent(jLabelCCV))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCard)
                                    .addComponent(jTextExpDate)
                                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelTotalView)
                                            .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 44, Short.MAX_VALUE))))
                            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonProceed)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCheckoutLayout.setVerticalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckoutLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHolderName)
                    .addComponent(jTextHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCard)
                    .addComponent(jTextCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExpDate)
                    .addComponent(jTextExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCCV)
                    .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTotalView))
                .addGap(20, 20, 20)
                .addComponent(jButtonProceed)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelNewLayout = new javax.swing.GroupLayout(jPanelNew);
        jPanelNew.setLayout(jPanelNewLayout);
        jPanelNewLayout.setHorizontalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelAddBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabelQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonAddBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDeleteLine)
                .addGap(18, 18, 18)
                .addComponent(jButtonClearCart)
                .addGap(36, 36, 36))
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCartN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNewLayout.setVerticalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAddBook)
                    .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBook)
                    .addComponent(jLabelQuantity)
                    .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeleteLine)
                    .addComponent(jButtonClearCart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCartN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("New", jPanelNew);

        add(jTabbedPaneOrders, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jTextZipShippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipShippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipShippActionPerformed

    private void jTextZipBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonClearCart;
    private javax.swing.JButton jButtonDeleteLine;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSetStatus;
    private javax.swing.JComboBox<String> jComboBoxOrderStatus;
    private javax.swing.JLabel jLabelAddBook;
    private javax.swing.JLabel jLabelCCV;
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelCityBill;
    private javax.swing.JLabel jLabelCityShipp;
    private javax.swing.JLabel jLabelExpDate;
    private javax.swing.JLabel jLabelFirstNameBill;
    private javax.swing.JLabel jLabelFirstNameShipp;
    private javax.swing.JLabel jLabelHolderName;
    private javax.swing.JLabel jLabelLastNameBill;
    private javax.swing.JLabel jLabelLastNameShipp;
    private javax.swing.JLabel jLabelOrderStatus;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelStreetBill;
    private javax.swing.JLabel jLabelStreetShipp;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalView;
    private javax.swing.JLabel jLabelZipBill;
    private javax.swing.JLabel jLabelZipShipp;
    private javax.swing.JPanel jPanelBilling;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelCartN;
    private javax.swing.JPanel jPanelCheckout;
    private javax.swing.JPanel jPanelManage;
    private javax.swing.JPanel jPanelNew;
    private javax.swing.JPanel jPanelOrdersWaiting;
    private javax.swing.JPanel jPanelSearchOrder;
    private javax.swing.JPanel jPanelShipping;
    private javax.swing.JRadioButton jRadioButtonSame;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneCart;
    private javax.swing.JScrollPane jScrollPaneOrdersWaiting;
    private javax.swing.JTabbedPane jTabbedPaneOrders;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextAddBook;
    private javax.swing.JTextField jTextCCV;
    private javax.swing.JTextField jTextCard;
    private javax.swing.JTextField jTextCityBill;
    private javax.swing.JTextField jTextCityShipp;
    private javax.swing.JTextField jTextExpDate;
    private javax.swing.JTextField jTextFirstNameBill;
    private javax.swing.JTextField jTextFirstNameShipp;
    private javax.swing.JTextField jTextHolderName;
    private javax.swing.JTextField jTextLastNameBill;
    private javax.swing.JTextField jTextLastNameShipp;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTextField jTextStreetBill;
    private javax.swing.JTextField jTextStreetShipp;
    private javax.swing.JTextField jTextZipBill;
    private javax.swing.JTextField jTextZipShipp;
    // End of variables declaration//GEN-END:variables
}
