/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

import com.cdi.g3.common.exception.CheckException;
import com.cdi.g3.common.exception.FinderException;
import com.cdi.g3.common.logging.Trace;
import com.cdi.g3.server.domain.customers.Adress;
import com.cdi.g3.server.domain.customers.Customer;
import com.cdi.g3.server.service.customers.AdressService;
import com.cdi.g3.server.service.customers.CustomerService;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Apotheas
 */
public class JPanelFormCustomers extends javax.swing.JPanel {

    /**
     * Creates new form Accounts
     */
    public JPanelFormCustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAccounts = new javax.swing.JPanel();
        jScrollPaneTree = new javax.swing.JScrollPane();
        jTreeCustomers = new javax.swing.JTree();
        jPanelManage = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jPanelAccount = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<String>();
        jTextFirstName = new javax.swing.JTextField();
        jTextPassword = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jTextLogin = new javax.swing.JTextField();
        jButtonCreate = new javax.swing.JButton();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jTextLastName = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jLabelCompany = new javax.swing.JLabel();
        jTextCompany = new javax.swing.JTextField();
        jPanelShippingAdress = new javax.swing.JPanel();
        jLabeNameReceiverAdressShipp = new javax.swing.JLabel();
        jTextNameReceiverAdressShipp = new javax.swing.JTextField();
        jLabelIdAdressShipp = new javax.swing.JLabel();
        jTextIdAdressShipp = new javax.swing.JTextField();
        jLabelStreetShipp = new javax.swing.JLabel();
        jLabelZipCodeShipp = new javax.swing.JLabel();
        jLabelCityShipp = new javax.swing.JLabel();
        jTextStreetShipp = new javax.swing.JTextField();
        jTextCityShipp = new javax.swing.JTextField();
        jTextZipCodeShipp = new javax.swing.JTextField();
        jPanelBillingAddress = new javax.swing.JPanel();
        jLabelZipCodeBill = new javax.swing.JLabel();
        jTextCityBill = new javax.swing.JTextField();
        jLabelNameReceiverAdressBill = new javax.swing.JLabel();
        jTextIdAdressBill = new javax.swing.JTextField();
        jTextNameReceiverAdressBill = new javax.swing.JTextField();
        jTextZipCodeBill = new javax.swing.JTextField();
        jLabelStreetBill = new javax.swing.JLabel();
        jLabelIdAdressBill = new javax.swing.JLabel();
        jTextStreetBill = new javax.swing.JTextField();
        jLabelCityBill = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTreeCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder("Profils"));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Status");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Active");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BlackListed");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeCustomers.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPaneTree.setViewportView(jTreeCustomers);

        jPanelManage.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage"));

        jLabelSearch.setText("id/pseudo/email  :");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSearch.setText("search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelManageLayout = new javax.swing.GroupLayout(jPanelManage);
        jPanelManage.setLayout(jPanelManageLayout);
        jPanelManageLayout.setHorizontalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSearch)
                .addGap(18, 18, 18)
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUpdate)
                .addGap(18, 18, 18)
                .addComponent(jButtonDelete)
                .addGap(22, 22, 22))
        );
        jPanelManageLayout.setVerticalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonSearch))
                .addGap(35, 35, 35))
        );

        jPanelAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));

        jLabelEmail.setText("Email  :");

        jLabelLogin.setText("Login  :");

        jLabelStatus.setText("Status  :");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "BlackList", "Item 3", "Item 4" }));

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });

        jLabelPassword.setText("Password  :");

        jTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLoginActionPerformed(evt);
            }
        });

        jButtonCreate.setText("Create");

        jLabelFirstName.setText("First name :");

        jLabelLastName.setText("Last  name :");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jLabelCompany.setText("Company  : ");

        jTextCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompanyActionPerformed(evt);
            }
        });

        jPanelShippingAdress.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping adress"));

        jLabeNameReceiverAdressShipp.setText("Last Name  :");

        jLabelIdAdressShipp.setText("Id Adress Ship");

        jLabelStreetShipp.setText("Street   :");

        jLabelZipCodeShipp.setText("Zip Code  :");

        jLabelCityShipp.setText("City  :");

        jTextZipCodeShipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeShippActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShippingAdressLayout = new javax.swing.GroupLayout(jPanelShippingAdress);
        jPanelShippingAdress.setLayout(jPanelShippingAdressLayout);
        jPanelShippingAdressLayout.setHorizontalGroup(
            jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabelIdAdressShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextIdAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabelCityShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabelZipCodeShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabelStreetShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabeNameReceiverAdressShipp)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelShippingAdressLayout.setVerticalGroup(
            jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAdressShipp)
                    .addComponent(jTextIdAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNameReceiverAdressShipp)
                    .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetShipp)
                    .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jLabelZipCodeShipp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelShippingAdressLayout.createSequentialGroup()
                        .addComponent(jTextZipCodeShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelShippingAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCityShipp))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        jPanelBillingAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing adress"));

        jLabelZipCodeBill.setText("Zip Code  :");

        jLabelNameReceiverAdressBill.setText("Last Name  :");

        jTextZipCodeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeBillActionPerformed(evt);
            }
        });

        jLabelStreetBill.setText("Street   :");

        jLabelIdAdressBill.setText("Id Adress Bill");

        jLabelCityBill.setText("City  :");

        javax.swing.GroupLayout jPanelBillingAddressLayout = new javax.swing.GroupLayout(jPanelBillingAddress);
        jPanelBillingAddress.setLayout(jPanelBillingAddressLayout);
        jPanelBillingAddressLayout.setHorizontalGroup(
            jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jLabelIdAdressBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jLabelCityBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jLabelZipCodeBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jLabelStreetBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jLabelNameReceiverAdressBill)
                        .addGap(12, 12, 12)
                        .addComponent(jTextNameReceiverAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelBillingAddressLayout.setVerticalGroup(
            jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAdressBill)
                    .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameReceiverAdressBill)
                    .addComponent(jTextNameReceiverAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetBill)
                    .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZipCodeBill)
                    .addGroup(jPanelBillingAddressLayout.createSequentialGroup()
                        .addComponent(jTextZipCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBillingAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCityBill))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAccountLayout = new javax.swing.GroupLayout(jPanelAccount);
        jPanelAccount.setLayout(jPanelAccountLayout);
        jPanelAccountLayout.setHorizontalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createSequentialGroup()
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccountLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelShippingAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAccountLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelAccountLayout.createSequentialGroup()
                                .addComponent(jLabelFirstName)
                                .addGap(21, 21, 21)
                                .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAccountLayout.createSequentialGroup()
                                .addComponent(jLabelLastName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelAccountLayout.createSequentialGroup()
                                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(jTextLogin))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createSequentialGroup()
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelAccountLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabelStatus)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelAccountLayout.createSequentialGroup()
                                    .addComponent(jLabelCompany)
                                    .addGap(20, 20, 20)
                                    .addComponent(jTextCompany)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createSequentialGroup()
                                .addComponent(jLabelPassword)
                                .addGap(18, 18, 18)
                                .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addComponent(jPanelBillingAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCreate)
                .addGap(25, 25, 25))
        );
        jPanelAccountLayout.setVerticalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin))
                .addGap(18, 18, 18)
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccountLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAccountLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelCompany)
                                    .addComponent(jTextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPassword)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jPanelBillingAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCreate))
                    .addGroup(jPanelAccountLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFirstName))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLastName)
                            .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jPanelShippingAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout jPanelAccountsLayout = new javax.swing.GroupLayout(jPanelAccounts);
        jPanelAccounts.setLayout(jPanelAccountsLayout);
        jPanelAccountsLayout.setHorizontalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTree, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addComponent(jPanelManage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addComponent(jPanelAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(264, 264, 264))))
        );
        jPanelAccountsLayout.setVerticalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTree, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGroup(jPanelAccountsLayout.createSequentialGroup()
                        .addComponent(jPanelManage, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        add(jPanelAccounts, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jTextCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompanyActionPerformed

    private void jTextZipCodeBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeBillActionPerformed

    private void jTextZipCodeShippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeShippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeShippActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
      final String mname = "jButtonUpdateActionPerformed";
       
        CustomerService serviceCustomer = new CustomerService();
        AdressService serviceAdress = new AdressService();
        Customer customer = null;
        try {
            // Sets all the customer data
            //customer customerf = serviceCustomer.findCustomer(Id);
        
            customer = new Customer( jTextFirstName.getText(), jTextLastName.getText(), jTextEmail.getText(),jTextPassword.getText() );
            customer.setPasswordCustomer(jTextPassword.getText());
            System.out.println(jTextPassword.getText() );
            
            
            
            Adress adressShipping =  new Adress(jTextIdAdressShipp.getText());
            adressShipping.setNameStreetAdress(jTextNameReceiverAdressShipp.getText()); 
            adressShipping.setNameStreetAdress(jTextStreetShipp.getText()); 
            adressShipping.setNameStreetAdress(jTextZipCodeShipp.getText()); 
            adressShipping.setNameStreetAdress(jTextCityShipp.getText()); 
            adressShipping.setNameStreetAdress(jTextStreetShipp.getText()); 
            adressShipping.setCustomerShipAdress(customer);             
            serviceAdress.updateAdress(adressShipping); 
            
            Adress adressBilling =  new Adress(jTextIdAdressBill.getText());
            adressBilling.setNameStreetAdress(jTextNameReceiverAdressBill.getText()); 
            adressBilling.setNameStreetAdress(jTextStreetBill.getText()); 
            adressBilling.setNameStreetAdress(jTextZipCodeBill.getText()); 
            adressBilling.setNameStreetAdress(jTextCityBill.getText()); 
            adressBilling.setNameStreetAdress(jTextStreetBill.getText()); 
            adressBilling.setCustomerBillAdress(customer);            
            serviceAdress.updateAdress(adressBilling);
            
            
            
            
            // Asks if we want to remove the customer
        final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to update customer "
                +customer.getId() + " " +customer.getLastNameCustomer(), "Delete", JOptionPane.YES_NO_OPTION);
        if (anwser == JOptionPane.NO_OPTION) {
            return;
        }
         
        serviceCustomer.updateCustomer(customer);
                  
            
           
            
           
            // Create the customer
            JOptionPane.showMessageDialog(this, "Customer number "+customer.getId() + 
                    " is updeted", "info message", JOptionPane.INFORMATION_MESSAGE);
                        
//            jComboBoxCarnet.setModel(initCarnetModel());
//            jTree1.setModel(initCarnetTreeModel());

            //textContactId.setText(contact.getIdContact());
            //textContactDate.setText(DateFormat.getDateInstance().format(result.getContactDate()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
        
        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        try {
            CustomerService serviceCustomer = new CustomerService();
            Customer customer = serviceCustomer.findCustomer(jTextSearch.getText());
            
            jTextLogin.setText(customer.getLoginCustomer());
            jTextFirstName.setText(customer.getFirstNameCustomer());
            jTextLastName.setText(customer.getLastNameCustomer());
            jTextEmail.setText(customer.getEmailCustomer());            
            jTextPassword.setText(customer.getPasswordCustomer());
            
            for (Iterator iterator = customer.getListAddressShipping().iterator(); iterator.hasNext();) {
                final Adress adressShipping = (Adress) iterator.next();
                jTextNameReceiverAdressShipp.setText(adressShipping.getNameReceiverAdress());
                jTextStreetShipp.setText(adressShipping.getNameStreetAdress());
                jTextZipCodeShipp.setText(adressShipping.getZipcodeAdress());
                jTextCityShipp.setText(adressShipping.getCityAdress());
                jTextCompany.setText(adressShipping.getNameCompanyReceiverAdress().getNameCompany());
                jTextIdAdressShipp.setText(adressShipping.getId());
            }

            for (Iterator iterator = customer.getListAddressBilling().iterator(); iterator.hasNext();) {
                final Adress adressBilling = (Adress) iterator.next();
                jTextNameReceiverAdressBill.setText(adressBilling.getNameReceiverAdress());
                jTextStreetBill.setText(adressBilling.getNameStreetAdress());
                jTextZipCodeBill.setText(adressBilling.getZipcodeAdress());
                jTextCityBill.setText(adressBilling.getCityAdress());
                jTextCompany.setText(adressBilling.getNameCompanyReceiverAdress().getNameCompany());
                jTextIdAdressBill.setText(adressBilling.getId());
            }

        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CheckException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLoginActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        final String mname = "jButtonDeleteActionPerformed";

        final String customerId = jTextSearch.getText();
        if ("".equals(customerId)) {
            JOptionPane.showMessageDialog(this, "You have to enter an customer login ", "Delete", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Asks if we want to remove the customer
        final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to remove customer login " + customerId, "Delete", JOptionPane.YES_NO_OPTION);
        if (anwser == JOptionPane.NO_OPTION) {
            return;
        }

        final CustomerService serviceCustomer = new CustomerService();
        try {
            serviceCustomer.deleteCustomer(customerId);
            
            JOptionPane.showMessageDialog(this, "Customer login "+ customerId + 
                    " is deleted", "info message", JOptionPane.INFORMATION_MESSAGE);
            
//            jComboBoxCarnet.setModel(initCarnetModel());
//            jTree1.setModel(initCarnetTreeModel());
//            clearFrame();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        } // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    protected final transient String _cname = this.getClass().getName();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreate;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabeNameReceiverAdressShipp;
    private javax.swing.JLabel jLabelCityBill;
    private javax.swing.JLabel jLabelCityShipp;
    private javax.swing.JLabel jLabelCompany;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelIdAdressBill;
    private javax.swing.JLabel jLabelIdAdressShipp;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNameReceiverAdressBill;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStreetBill;
    private javax.swing.JLabel jLabelStreetShipp;
    private javax.swing.JLabel jLabelZipCodeBill;
    private javax.swing.JLabel jLabelZipCodeShipp;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelAccounts;
    private javax.swing.JPanel jPanelBillingAddress;
    private javax.swing.JPanel jPanelManage;
    private javax.swing.JPanel jPanelShippingAdress;
    private javax.swing.JScrollPane jScrollPaneTree;
    private javax.swing.JTextField jTextCityBill;
    private javax.swing.JTextField jTextCityShipp;
    private javax.swing.JTextField jTextCompany;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextIdAdressBill;
    private javax.swing.JTextField jTextIdAdressShipp;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextNameReceiverAdressBill;
    private javax.swing.JTextField jTextNameReceiverAdressShipp;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTextField jTextStreetBill;
    private javax.swing.JTextField jTextStreetShipp;
    private javax.swing.JTextField jTextZipCodeBill;
    private javax.swing.JTextField jTextZipCodeShipp;
    private javax.swing.JTree jTreeCustomers;
    // End of variables declaration//GEN-END:variables
}
