/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

import com.cdi.g3.common.exception.FinderException;
import com.cdi.g3.common.exception.ObjectNotFoundException;
import com.cdi.g3.common.logging.Trace;
import com.cdi.g3.server.domain.catalog.Book;
import com.cdi.g3.server.domain.catalog.BookDAO;
import com.cdi.g3.server.domain.customers.Adress;
import com.cdi.g3.server.domain.customers.Customer;
import com.cdi.g3.server.domain.orders.OrderLine;
import com.cdi.g3.server.domain.orders.Orders;
import com.cdi.g3.server.service.catalog.CatalogService;
import com.cdi.g3.server.service.customers.CustomerService;
import com.cdi.g3.server.service.orders.OrderService;
import java.text.DateFormat;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Apotheas
 */
//public class JPanelFormOrders extends javax.swing.JPanel {
    public class JPanelFormOrders extends  JDesktopPane{
//    CatalogService bookService = new CatalogService();
    
    /**
     * Creates new form JPanelOrders
     */
    public JPanelFormOrders() {
        initComponents(); 
        
        
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneOrders = new javax.swing.JTabbedPane();
        jPanelManage = new javax.swing.JPanel();
        jPanelSearchOrder = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jLabelOrderStatus = new javax.swing.JLabel();
        jComboBoxOrderStatus = new javax.swing.JComboBox<String>();
        jButtonSearch = new javax.swing.JButton();
        jPanelCart = new javax.swing.JPanel();
        jScrollPaneCart = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButtonSetStatus = new javax.swing.JButton();
        jPanelOrdersWaiting = new javax.swing.JPanel();
        jScrollPaneOrdersWaiting = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanelNew = new javax.swing.JPanel();
        jPanelCartN = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableShoppingCart = new javax.swing.JTable();
        jTextAddBook = new javax.swing.JTextField();
        jButtonAddBook = new javax.swing.JButton();
        jLabelQuantity = new javax.swing.JLabel();
        jTextQuantity = new javax.swing.JTextField();
        jButtonDeleteLine = new javax.swing.JButton();
        jButtonClearCart = new javax.swing.JButton();
        jPanelShipping = new javax.swing.JPanel();
        jLabelLastNameShipp = new javax.swing.JLabel();
        jTextLastNameShip = new javax.swing.JTextField();
        jLabelIdAdressShipp = new javax.swing.JLabel();
        jTextIdAdressShip = new javax.swing.JTextField();
        jLabelStreetShipp = new javax.swing.JLabel();
        jLabelZipShipp = new javax.swing.JLabel();
        jLabelCityShipp = new javax.swing.JLabel();
        jTextStreetShip = new javax.swing.JTextField();
        jTextCityShip = new javax.swing.JTextField();
        jTextZipShip = new javax.swing.JTextField();
        jTextStreet2Ship = new javax.swing.JTextField();
        jLabelStreet2Ship = new javax.swing.JLabel();
        jTextNumAdressShip = new javax.swing.JTextField();
        jLabelNumAdressShip = new javax.swing.JLabel();
        jLabelCountryShip = new javax.swing.JLabel();
        jTextCountryShip = new javax.swing.JTextField();
        jPanelBilling = new javax.swing.JPanel();
        jLabelZipBill = new javax.swing.JLabel();
        jTextCityBill = new javax.swing.JTextField();
        jLabelLastNameBill = new javax.swing.JLabel();
        jTextIdAdressBill = new javax.swing.JTextField();
        jTextLastNameBill = new javax.swing.JTextField();
        jTextZipBill = new javax.swing.JTextField();
        jLabelStreetBill = new javax.swing.JLabel();
        jLabelIdAdressBill = new javax.swing.JLabel();
        jTextStreetBill = new javax.swing.JTextField();
        jLabelCityBill = new javax.swing.JLabel();
        jTextStreet2AdressBill = new javax.swing.JTextField();
        jLabelStreet2AdressBill = new javax.swing.JLabel();
        jTextNumAdressBill = new javax.swing.JTextField();
        jLabelNumAdressBill = new javax.swing.JLabel();
        jTextCoutryAdressBill = new javax.swing.JTextField();
        jLabelCoutryAdressBill = new javax.swing.JLabel();
        jPanelCheckout = new javax.swing.JPanel();
        jButtonProceed = new javax.swing.JButton();
        jLabelHolderName = new javax.swing.JLabel();
        jTextHolderName = new javax.swing.JTextField();
        jLabelCard = new javax.swing.JLabel();
        jLabelExpDate = new javax.swing.JLabel();
        jLabelCCV = new javax.swing.JLabel();
        jTextCard = new javax.swing.JTextField();
        jTextExpDate = new javax.swing.JTextField();
        jTextCCV = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelTotalView = new javax.swing.JLabel();
        jTextOrderId = new javax.swing.JTextField();
        jTextOrderDate = new javax.swing.JTextField();
        jComboBoxCustomer = new javax.swing.JComboBox();
        jComboBoxBook = new javax.swing.JComboBox();
        jLabelComboBoxCustmers = new javax.swing.JLabel();
        jComboBoxCreteriaSearchBook = new javax.swing.JComboBox();
        jLabelComboBoxBooks = new javax.swing.JLabel();
        jComboBoxAdressShipping = new javax.swing.JComboBox();
        jComboBoxAdressBilling = new javax.swing.JComboBox();
        jRadioButtonSame = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanelSearchOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Search order"));

        jLabelSearch.setText("Order id / User  : ");

        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });

        jLabelOrderStatus.setText("Order Status  :");

        jComboBoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shipped", "Item 2", "Item 3", "Item 4" }));

        jButtonSearch.setText("Search");

        jPanelCart.setBorder(javax.swing.BorderFactory.createTitledBorder("Shopping Cart"));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Title", "Author", "Quantity"
            }
        ));
        jScrollPaneCart.setViewportView(jTable5);

        javax.swing.GroupLayout jPanelCartLayout = new javax.swing.GroupLayout(jPanelCart);
        jPanelCart.setLayout(jPanelCartLayout);
        jPanelCartLayout.setHorizontalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart)
        );
        jPanelCartLayout.setVerticalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );

        jButtonSetStatus.setText("Set");

        javax.swing.GroupLayout jPanelSearchOrderLayout = new javax.swing.GroupLayout(jPanelSearchOrder);
        jPanelSearchOrder.setLayout(jPanelSearchOrderLayout);
        jPanelSearchOrderLayout.setHorizontalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelSearch)
                .addGap(110, 110, 110)
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabelOrderStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSetStatus)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSearchOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSearchOrderLayout.setVerticalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearch)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderStatus)
                    .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonSetStatus))
                .addGap(18, 18, 18)
                .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanelOrdersWaiting.setBorder(javax.swing.BorderFactory.createTitledBorder("Orders waiting for Traitment"));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID ", "User", "Adresse", "Date"
            }
        ));
        jScrollPaneOrdersWaiting.setViewportView(jTable6);

        javax.swing.GroupLayout jPanelOrdersWaitingLayout = new javax.swing.GroupLayout(jPanelOrdersWaiting);
        jPanelOrdersWaiting.setLayout(jPanelOrdersWaitingLayout);
        jPanelOrdersWaitingLayout.setHorizontalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting)
                .addContainerGap())
        );
        jPanelOrdersWaitingLayout.setVerticalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelManageLayout = new javax.swing.GroupLayout(jPanelManage);
        jPanelManage.setLayout(jPanelManageLayout);
        jPanelManageLayout.setHorizontalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelManageLayout.setVerticalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("Manage", jPanelManage);

        jPanelNew.setBorder(javax.swing.BorderFactory.createTitledBorder("New Order"));

        jPanelCartN.setBorder(javax.swing.BorderFactory.createTitledBorder("Shopping Cart"));

        jTableShoppingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Quantity", "Cost", "Tva", "Prix HT", "Prix TTC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableShoppingCart);

        javax.swing.GroupLayout jPanelCartNLayout = new javax.swing.GroupLayout(jPanelCartN);
        jPanelCartN.setLayout(jPanelCartNLayout);
        jPanelCartNLayout.setHorizontalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        jPanelCartNLayout.setVerticalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCartNLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jButtonAddBook.setText("Add");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jLabelQuantity.setText("Quantity  :");

        jButtonDeleteLine.setText("Delete");

        jButtonClearCart.setText("Clear");

        jPanelShipping.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Adress"));

        jLabelLastNameShipp.setText("Last Name  :");

        jLabelIdAdressShipp.setText("IdAdressShip");

        jLabelStreetShipp.setText("Street   :");

        jLabelZipShipp.setText("Zip Code  :");

        jLabelCityShipp.setText("City  :");

        jTextZipShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipShipActionPerformed(evt);
            }
        });

        jLabelStreet2Ship.setText("Street2");

        jLabelNumAdressShip.setText("num Adress");

        jLabelCountryShip.setText("Country");

        javax.swing.GroupLayout jPanelShippingLayout = new javax.swing.GroupLayout(jPanelShipping);
        jPanelShipping.setLayout(jPanelShippingLayout);
        jPanelShippingLayout.setHorizontalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelIdAdressShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jTextIdAdressShip, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelLastNameShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextLastNameShip, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelZipShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipShip, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelStreet2Ship)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreet2Ship, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStreetShipp)
                            .addComponent(jLabelNumAdressShip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNumAdressShip)
                            .addComponent(jTextStreetShip, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCityShipp)
                            .addComponent(jLabelCountryShip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCityShip, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextCountryShip))))
                .addContainerGap())
        );
        jPanelShippingLayout.setVerticalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastNameShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastNameShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumAdressShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumAdressShip))
                .addGap(8, 8, 8)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreetShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetShipp))
                .addGap(11, 11, 11)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Ship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Ship))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCityShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCityShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountryShip)
                    .addComponent(jTextCountryShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelBilling.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing Adress"));

        jLabelZipBill.setText("Zip Code  :");

        jLabelLastNameBill.setText("Last Name  :");

        jTextZipBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipBillActionPerformed(evt);
            }
        });

        jLabelStreetBill.setText("Street   :");

        jLabelIdAdressBill.setText("IdAdressBill");

        jLabelCityBill.setText("City  :");

        jLabelStreet2AdressBill.setText("Steet2");

        jLabelNumAdressBill.setText("jLabel2");

        jLabelCoutryAdressBill.setText("Country");

        javax.swing.GroupLayout jPanelBillingLayout = new javax.swing.GroupLayout(jPanelBilling);
        jPanelBilling.setLayout(jPanelBillingLayout);
        jPanelBillingLayout.setHorizontalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jLabelZipBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdAdressBill)
                            .addComponent(jLabelLastNameBill)
                            .addComponent(jLabelStreetBill)
                            .addComponent(jLabelStreet2AdressBill)
                            .addComponent(jLabelNumAdressBill))
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBillingLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextNumAdressBill)
                                    .addComponent(jTextLastNameBill, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(jTextStreetBill, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jTextStreet2AdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCityBill)
                            .addComponent(jLabelCoutryAdressBill))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCoutryAdressBill)
                            .addComponent(jTextCityBill, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelBillingLayout.setVerticalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAdressBill)
                    .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLastNameBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastNameBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumAdressBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2AdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2AdressBill))
                .addGap(7, 7, 7)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelZipBill)
                            .addComponent(jTextZipBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBillingLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelCityBill)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCoutryAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCoutryAdressBill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCheckout.setBorder(javax.swing.BorderFactory.createTitledBorder("Checkout"));

        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jLabelHolderName.setText("Holder name  :");

        jLabelCard.setText("Card number  :");

        jLabelExpDate.setText("Exp Date  :");

        jLabelCCV.setText("CCV  :");

        jLabelTotal.setText("Total  TTC  :");

        jLabelTotalView.setText("99.99 €");

        javax.swing.GroupLayout jPanelCheckoutLayout = new javax.swing.GroupLayout(jPanelCheckout);
        jPanelCheckout.setLayout(jPanelCheckoutLayout);
        jPanelCheckoutLayout.setHorizontalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckoutLayout.createSequentialGroup()
                                .addComponent(jLabelHolderName)
                                .addGap(18, 18, 18)
                                .addComponent(jTextHolderName))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCheckoutLayout.createSequentialGroup()
                                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCard)
                                    .addComponent(jLabelExpDate)
                                    .addComponent(jLabelCCV))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCard)
                                    .addComponent(jTextExpDate)
                                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelTotalView)
                                            .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(16, 16, 16))
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotal)
                            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                                .addComponent(jTextOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonProceed)
                .addContainerGap())
        );
        jPanelCheckoutLayout.setVerticalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckoutLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHolderName)
                    .addComponent(jTextHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCard)
                    .addComponent(jTextCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExpDate)
                    .addComponent(jTextExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCCV)
                    .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTotalView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProceed)
                .addGap(5, 5, 5)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jComboBoxCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxBookMouseClicked(evt);
            }
        });
        jComboBoxBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBookActionPerformed(evt);
            }
        });

        jLabelComboBoxCustmers.setText("Select a customer");

        jComboBoxCreteriaSearchBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Titre" }));

        jLabelComboBoxBooks.setText("Select a Book");

        jComboBoxAdressShipping.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxAdressBilling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRadioButtonSame.setText("Same as Shipping");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNewLayout = new javax.swing.GroupLayout(jPanelNew);
        jPanelNew.setLayout(jPanelNewLayout);
        jPanelNewLayout.setHorizontalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCartN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNewLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBoxCreteriaSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabelComboBoxBooks)
                                .addGap(39, 39, 39)
                                .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuantity)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddBook))
                                .addGap(86, 86, 86)
                                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonDeleteLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonClearCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelNewLayout.createSequentialGroup()
                                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelNewLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jComboBoxAdressShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelNewLayout.createSequentialGroup()
                                        .addComponent(jComboBoxAdressBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonSame)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelNewLayout.createSequentialGroup()
                                        .addComponent(jPanelBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanelCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNewLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelComboBoxCustmers)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelNewLayout.setVerticalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCreteriaSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantity)
                            .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearCart)
                            .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComboBoxBooks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddBook)
                            .addComponent(jButtonDeleteLine))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCartN, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComboBoxCustmers)
                    .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAdressShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAdressBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSame))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanelShipping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(271, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("New", jPanelNew);

        jTable1.setModel(initOrdersTableModel());
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jTabbedPaneOrders.addTab("Orders", jTabbedPane1);

        add(jTabbedPaneOrders, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        final String mname = "jButtonAddBookActionPerformed";
        final CustomerService customerService = new CustomerService();  
        JPanelFormCustomers jPanalCustomer = new JPanelFormCustomers();
        try {
//            if (jComboBoxCustomer.equals(null)) {
            final Collection  customers = customerService.findCustomers();
            jComboBoxCustomer.setModel(jPanalCustomer.initCustomersComboBoxModel(customers));
//            }
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        Book book =  (Book) jComboBoxBook.getSelectedItem();
        jTableShoppingCart.setValueAt(book.getId(),0, 0);
        jTableShoppingCart.setValueAt(jTextQuantity.getText(),0, 1);
        jTableShoppingCart.setValueAt(book.getUnitCostBook(),0, 2);
        
        System.out.println(book.getCodeTVA().getRateCodeTva());
        
        
        jTableShoppingCart.setValueAt(book.getCodeTVA().getRateCodeTva(),0, 3);
        float prixHT = Integer.parseInt(jTextQuantity.getText())*book.getCodeTVA().getRateCodeTva();
        float prixTCC = prixHT * book.getCodeTVA().getRateCodeTva();
        jTableShoppingCart.setValueAt(prixHT,0, 4);
        jTableShoppingCart.setValueAt(prixTCC,0, 5);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jTextZipShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipShipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipShipActionPerformed

    private void jTextZipBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipBillActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
    final String mname = "jButtonProceedActionPerformed";
        final OrderService OrderService = new OrderService();
    final CustomerService customerService = new CustomerService();
        final Orders order;
        try {
            // Sets all the Order data
            order = new Orders();            
            
            // Sets all the order items data
            final Collection orderLines = new ArrayList();            
            OrderLine orderLine;
            for(int i=0; i< this.jTableShoppingCart.getRowCount(); i++) {                       
                
                    orderLine = new OrderLine(new Book( (String) jTableShoppingCart.getModel().getValueAt(0,1)), 
                            (int) jTableShoppingCart.getModel().getValueAt(1,i),
                             (float) jTableShoppingCart.getModel().getValueAt(2,i),
                            (float) jTableShoppingCart.getModel().getValueAt(3,i) );                        
                    
                    orderLines.add(orderLine);
            }
            
             // Sets all the Order data
            final Customer customer = ((Customer) jComboBoxCustomer.getSelectedItem());
            order.setCustomer(customer);
            order.setDateOrder(new Date());
            order.setPaymentSystemOrder("CB");
            
            if (jTextIdAdressShip.getText()== null|| jTextIdAdressShip.getText().isEmpty())
                JOptionPane.showMessageDialog(this, "select a customer", "info message", JOptionPane.INFORMATION_MESSAGE);
            
            order.setAdressShipping(new Adress(jTextIdAdressShip.getText()));
            order.setAdressBilling(new Adress(jTextIdAdressBill.getText()));
            order.setListOrderLines(orderLines);
            
            // Create the order
            
            final Orders result = OrderService.createOrder(order);
            jTextOrderId.setText(result.getId());
            jTextOrderDate.setText(DateFormat.getDateInstance().format(result.getDateOrder()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
    }//GEN-LAST:event_jButtonProceedActionPerformed

    private void jComboBoxBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBookActionPerformed
            BookDAO _daoBook =new BookDAO();
                try {
              Collection books ;
                books = _daoBook.findAll();
                jComboBoxBook.setModel(initBooksComboBoxModel(books));
        } catch (ObjectNotFoundException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBookActionPerformed

    private void jComboBoxBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxBookMouseClicked
        BookDAO _daoBook =new BookDAO();
                try {
              Collection books ;
                books = _daoBook.findAll();
                jComboBoxBook.setModel(initBooksComboBoxModel(books));
        } catch (ObjectNotFoundException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        }  // TODO
    }//GEN-LAST:event_jComboBoxBookMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public DefaultComboBoxModel initBooksComboBoxModel(Collection books) {
        return new DefaultComboBoxModel( initBooksVector(books) );
    }
    private Vector initBooksVector(Collection books) {
        final String mname = "initAdressChipVector";
        Vector v = new Vector();
        v.addAll(books);
        return v;
    }
        
        
        
        
    public DefaultTableModel initOrdersTableModel() {
        return new DefaultTableModel(initVectorTableData(), initVectorColumnNamesTable());
    }
    
    private Vector initVectorTableData() {
       final String mname = "initVectorTableData";
       OrderService serviceOrder = new OrderService();
       Vector rowDada = new Vector();      
       Collection    orders = null;
        try {
            orders = serviceOrder.findOrders();
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
       for (Orders order : (Collection <Orders>) orders) {
           Vector colData = null;
           colData = new Vector();
           colData.add(order);
           rowDada.add(order.getVector());
       }
        return rowDada; 
    }

    private Vector initVectorColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("Order");
        columnNames.add("LOGIN");
        columnNames.add("Last Name");
        columnNames.add("First Name");
        columnNames.add("Adress Shipping");
        columnNames.add("Date Order");
        columnNames.add("Name Shipper");
        columnNames.add("Ip Customer");
        columnNames.add("Status Order");
        columnNames.add("Status");
        return columnNames;
    }
    
protected final transient String _cname = this.getClass().getName();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonClearCart;
    private javax.swing.JButton jButtonDeleteLine;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSetStatus;
    private javax.swing.JComboBox jComboBoxAdressBilling;
    private javax.swing.JComboBox jComboBoxAdressShipping;
    private javax.swing.JComboBox jComboBoxBook;
    private javax.swing.JComboBox jComboBoxCreteriaSearchBook;
    private javax.swing.JComboBox jComboBoxCustomer;
    private javax.swing.JComboBox<String> jComboBoxOrderStatus;
    private javax.swing.JLabel jLabelCCV;
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelCityBill;
    private javax.swing.JLabel jLabelCityShipp;
    private javax.swing.JLabel jLabelComboBoxBooks;
    private javax.swing.JLabel jLabelComboBoxCustmers;
    private javax.swing.JLabel jLabelCountryShip;
    private javax.swing.JLabel jLabelCoutryAdressBill;
    private javax.swing.JLabel jLabelExpDate;
    private javax.swing.JLabel jLabelHolderName;
    private javax.swing.JLabel jLabelIdAdressBill;
    private javax.swing.JLabel jLabelIdAdressShipp;
    private javax.swing.JLabel jLabelLastNameBill;
    private javax.swing.JLabel jLabelLastNameShipp;
    private javax.swing.JLabel jLabelNumAdressBill;
    private javax.swing.JLabel jLabelNumAdressShip;
    private javax.swing.JLabel jLabelOrderStatus;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelStreet2AdressBill;
    private javax.swing.JLabel jLabelStreet2Ship;
    private javax.swing.JLabel jLabelStreetBill;
    private javax.swing.JLabel jLabelStreetShipp;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalView;
    private javax.swing.JLabel jLabelZipBill;
    private javax.swing.JLabel jLabelZipShipp;
    private javax.swing.JPanel jPanelBilling;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelCartN;
    private javax.swing.JPanel jPanelCheckout;
    private javax.swing.JPanel jPanelManage;
    private javax.swing.JPanel jPanelNew;
    private javax.swing.JPanel jPanelOrdersWaiting;
    private javax.swing.JPanel jPanelSearchOrder;
    private javax.swing.JPanel jPanelShipping;
    private javax.swing.JRadioButton jRadioButtonSame;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneCart;
    private javax.swing.JScrollPane jScrollPaneOrdersWaiting;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneOrders;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTableShoppingCart;
    private javax.swing.JTextField jTextAddBook;
    private javax.swing.JTextField jTextCCV;
    private javax.swing.JTextField jTextCard;
    private javax.swing.JTextField jTextCityBill;
    private javax.swing.JTextField jTextCityShip;
    private javax.swing.JTextField jTextCountryShip;
    private javax.swing.JTextField jTextCoutryAdressBill;
    private javax.swing.JTextField jTextExpDate;
    private javax.swing.JTextField jTextHolderName;
    private javax.swing.JTextField jTextIdAdressBill;
    private javax.swing.JTextField jTextIdAdressShip;
    private javax.swing.JTextField jTextLastNameBill;
    private javax.swing.JTextField jTextLastNameShip;
    private javax.swing.JTextField jTextNumAdressBill;
    private javax.swing.JTextField jTextNumAdressShip;
    private javax.swing.JTextField jTextOrderDate;
    private javax.swing.JTextField jTextOrderId;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTextField jTextStreet2AdressBill;
    private javax.swing.JTextField jTextStreet2Ship;
    private javax.swing.JTextField jTextStreetBill;
    private javax.swing.JTextField jTextStreetShip;
    private javax.swing.JTextField jTextZipBill;
    private javax.swing.JTextField jTextZipShip;
    // End of variables declaration//GEN-END:variables
}
