/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

import com.cdi.g3.common.exception.CheckException;
import com.cdi.g3.common.exception.FinderException;
import com.cdi.g3.common.exception.ObjectNotFoundException;
import com.cdi.g3.common.logging.Trace;
import com.cdi.g3.common.utiles.Utility;
import com.cdi.g3.server.domain.catalog.Book;
import com.cdi.g3.server.domain.catalog.BookDAO;
import com.cdi.g3.server.domain.customers.Adress;
import com.cdi.g3.server.domain.customers.Customer;
import com.cdi.g3.server.domain.orders.InfoStatus;
import com.cdi.g3.server.domain.orders.OrderLine;
import com.cdi.g3.server.domain.orders.Orders;
import com.cdi.g3.server.domain.other.CodeTVA;
import com.cdi.g3.server.service.customers.CustomerService;
import com.cdi.g3.server.service.orders.OrderService;
import com.cdi.g3.server.service.other.OtherService;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Apotheas
 */
//public class JPanelFormOrders extends javax.swing.JPanel {
public class JPanelFormOrders extends JDesktopPane {
//    CatalogService bookService = new CatalogService();

    final CustomerService customerService = new CustomerService();
    JPanelFormCustomers jPanalCustomer = new JPanelFormCustomers();

    OrderService serviceOrder = new OrderService();
    OtherService otherService = new OtherService();
    BookDAO _daoBook = new BookDAO();
    Vector cartShopingData = new Vector();
    Vector<Orders> Ordersvector = new Vector();
    Vector<OrderLine> OrderLinesvector = new Vector();
    Collection books;

    /**
     * Creates new form JPanelOrders
     */
    public JPanelFormOrders() {
        initComponents();
        chargeComboBoxStatusOrders();
        chargeComboBoxBooks();
        chargeTableOrders();
        jPanalCustomer.chargeComboBoxCustomers();
        jTextIdAdressShipp.setEnabled(true);
        jTextIdAdressBill.setEnabled(false);

        jTableOrders.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                selectLineTableOrdersActionPerformed(evt);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneOrders = new javax.swing.JTabbedPane();
        jPanelManage = new javax.swing.JPanel();
        jPanelSearchOrder = new javax.swing.JPanel();
        jTextSearchOrders = new javax.swing.JTextField();
        jComboBoxOrderStatus = new javax.swing.JComboBox<String>();
        jButtonSearchOrders = new javax.swing.JButton();
        jPanelCart = new javax.swing.JPanel();
        jScrollPaneCart = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();
        jComboBoxSearchOrdersBycolumn = new javax.swing.JComboBox();
        jPanelOrdersWaiting = new javax.swing.JPanel();
        jScrollPaneOrdersWaiting = new javax.swing.JScrollPane();
        jTableOrdersLine = new javax.swing.JTable();
        jButtonUpdateOrder = new javax.swing.JButton();
        jPanelNew = new javax.swing.JPanel();
        jPanelCartN = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableShoppingCart = new javax.swing.JTable();
        jLbelTotalTCCView = new javax.swing.JLabel();
        jLabelTotalTCC = new javax.swing.JLabel();
        jLabelTotalHT = new javax.swing.JLabel();
        jLabelTotalHTView = new javax.swing.JLabel();
        jTextAddBook = new javax.swing.JTextField();
        jButtonAddBook = new javax.swing.JButton();
        jLabelQuantity = new javax.swing.JLabel();
        jTextQuantity = new javax.swing.JTextField();
        jButtonDeleteLine = new javax.swing.JButton();
        jButtonClearCart = new javax.swing.JButton();
        jPanelShipping = new javax.swing.JPanel();
        jLabelLastNameShipp = new javax.swing.JLabel();
        jTextNameReceiverAdressShipp = new javax.swing.JTextField();
        jLabelStreetShipp = new javax.swing.JLabel();
        jLabelZipShipp = new javax.swing.JLabel();
        jLabelCityShipp = new javax.swing.JLabel();
        jTextStreetShipp = new javax.swing.JTextField();
        jTextCityShipp = new javax.swing.JTextField();
        jTextZipCodeShipp = new javax.swing.JTextField();
        jTextStreet2Shipp = new javax.swing.JTextField();
        jLabelStreet2Ship = new javax.swing.JLabel();
        jTextNumStreetShipp = new javax.swing.JTextField();
        jLabelNumAdressShip = new javax.swing.JLabel();
        jLabelCountryShip = new javax.swing.JLabel();
        jTextCountryShipp = new javax.swing.JTextField();
        jTextIdAdressShipp = new javax.swing.JTextField();
        jLabelIdAdressShipp = new javax.swing.JLabel();
        jPanelBilling = new javax.swing.JPanel();
        jLabelZipBill = new javax.swing.JLabel();
        jTextCityBill = new javax.swing.JTextField();
        jLabelLastNameBill = new javax.swing.JLabel();
        jTextNameReceiverAdressBill = new javax.swing.JTextField();
        jTextZipCodeBill = new javax.swing.JTextField();
        jLabelStreetBill = new javax.swing.JLabel();
        jTextStreetBill = new javax.swing.JTextField();
        jLabelCityBill = new javax.swing.JLabel();
        jTextStreet2Bill = new javax.swing.JTextField();
        jLabelStreet2AdressBill = new javax.swing.JLabel();
        jTextNumStreetBill = new javax.swing.JTextField();
        jLabelNumAdressBill = new javax.swing.JLabel();
        jTextCountryBill = new javax.swing.JTextField();
        jLabelCoutryAdressBill = new javax.swing.JLabel();
        jTextIdAdressBill = new javax.swing.JTextField();
        jLabelIdAdressBill = new javax.swing.JLabel();
        jPanelCheckout = new javax.swing.JPanel();
        jButtonProceed = new javax.swing.JButton();
        jLabelHolderName = new javax.swing.JLabel();
        jTextHolderName = new javax.swing.JTextField();
        jLabelCard = new javax.swing.JLabel();
        jLabelExpDate = new javax.swing.JLabel();
        jLabelCCV = new javax.swing.JLabel();
        jTextCard = new javax.swing.JTextField();
        jTextExpDate = new javax.swing.JTextField();
        jTextCCV = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jLabelTotalView = new javax.swing.JLabel();
        jTextOrderId = new javax.swing.JTextField();
        jTextOrderDate = new javax.swing.JTextField();
        jComboBoxCustomer = new javax.swing.JComboBox();
        jComboBoxBook = new javax.swing.JComboBox();
        jLabelComboBoxCustmers = new javax.swing.JLabel();
        jComboBoxCreteriaSearchBook = new javax.swing.JComboBox();
        jLabelComboBoxBooks = new javax.swing.JLabel();
        jComboBoxAdressShipping = new javax.swing.JComboBox();
        jComboBoxAdressBilling = new javax.swing.JComboBox();
        jRadioButtonSame = new javax.swing.JRadioButton();
        jLabelDiscount = new javax.swing.JLabel();
        jTextDiscount = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanelSearchOrder.setBorder(javax.swing.BorderFactory.createTitledBorder("Search order"));

        jTextSearchOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchOrdersActionPerformed(evt);
            }
        });

        jComboBoxOrderStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Shipped", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOrderStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrderStatusActionPerformed(evt);
            }
        });

        jButtonSearchOrders.setText("Search");
        jButtonSearchOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchOrdersActionPerformed(evt);
            }
        });

        jPanelCart.setBorder(javax.swing.BorderFactory.createTitledBorder("Orders"));

        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num order", "Num intern order", "Date order", "LastName Customer", "FirstName Customer", "Name shipper", "Date shipping", "Ip customer", "Satatus order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneCart.setViewportView(jTableOrders);

        javax.swing.GroupLayout jPanelCartLayout = new javax.swing.GroupLayout(jPanelCart);
        jPanelCart.setLayout(jPanelCartLayout);
        jPanelCartLayout.setHorizontalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart)
        );
        jPanelCartLayout.setVerticalGroup(
            jPanelCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneCart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        jComboBoxSearchOrdersBycolumn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Number Order", "InternNum Order", "Login Customer" }));

        javax.swing.GroupLayout jPanelSearchOrderLayout = new javax.swing.GroupLayout(jPanelSearchOrder);
        jPanelSearchOrder.setLayout(jPanelSearchOrderLayout);
        jPanelSearchOrderLayout.setHorizontalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                        .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(jComboBoxSearchOrdersBycolumn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextSearchOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchOrders)
                        .addGap(0, 332, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSearchOrderLayout.setVerticalGroup(
            jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchOrders)
                    .addComponent(jComboBoxSearchOrdersBycolumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSearchOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanelCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPanelOrdersWaiting.setBorder(javax.swing.BorderFactory.createTitledBorder("Orders Lines"));

        jTableOrdersLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID ", "User", "Adresse", "Date"
            }
        ));
        jScrollPaneOrdersWaiting.setViewportView(jTableOrdersLine);

        javax.swing.GroupLayout jPanelOrdersWaitingLayout = new javax.swing.GroupLayout(jPanelOrdersWaiting);
        jPanelOrdersWaiting.setLayout(jPanelOrdersWaitingLayout);
        jPanelOrdersWaitingLayout.setHorizontalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting)
                .addContainerGap())
        );
        jPanelOrdersWaitingLayout.setVerticalGroup(
            jPanelOrdersWaitingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOrdersWaitingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneOrdersWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonUpdateOrder.setText("Update Order");

        javax.swing.GroupLayout jPanelManageLayout = new javax.swing.GroupLayout(jPanelManage);
        jPanelManage.setLayout(jPanelManageLayout);
        jPanelManageLayout.setHorizontalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUpdateOrder)
                .addGap(23, 23, 23))
        );
        jPanelManageLayout.setVerticalGroup(
            jPanelManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSearchOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelOrdersWaiting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("Manage", jPanelManage);

        jPanelNew.setBorder(javax.swing.BorderFactory.createTitledBorder("New Order"));

        jPanelCartN.setBorder(javax.swing.BorderFactory.createTitledBorder("Shopping Cart"));

        jTableShoppingCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Quantity", "Cost", "Tva", "Prix HT", "Prix TTC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableShoppingCart);

        jLbelTotalTCCView.setText("99.99 €");

        jLabelTotalTCC.setText("Total  TTC  :");

        jLabelTotalHT.setText("Total HT");

        javax.swing.GroupLayout jPanelCartNLayout = new javax.swing.GroupLayout(jPanelCartN);
        jPanelCartN.setLayout(jPanelCartNLayout);
        jPanelCartNLayout.setHorizontalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCartNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCartNLayout.createSequentialGroup()
                        .addComponent(jLabelTotalTCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLbelTotalTCCView, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCartNLayout.createSequentialGroup()
                        .addComponent(jLabelTotalHT)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalHTView, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelCartNLayout.setVerticalGroup(
            jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartNLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTotalHT)
                    .addComponent(jLabelTotalHTView, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCartNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotalTCC)
                    .addComponent(jLbelTotalTCCView))
                .addContainerGap())
        );

        jButtonAddBook.setText("Add");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jLabelQuantity.setText("Quantity  :");

        jButtonDeleteLine.setText("Delete");

        jButtonClearCart.setText("Clear");

        jPanelShipping.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Adress"));

        jLabelLastNameShipp.setText("Last Name  :");

        jLabelStreetShipp.setText("Street   :");

        jLabelZipShipp.setText("Zip Code  :");

        jLabelCityShipp.setText("City  :");

        jTextZipCodeShipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeShippActionPerformed(evt);
            }
        });

        jLabelStreet2Ship.setText("Street2");

        jLabelNumAdressShip.setText("num Adress");

        jLabelCountryShip.setText("Country");

        jLabelIdAdressShipp.setText("IdAdressShip");

        javax.swing.GroupLayout jPanelShippingLayout = new javax.swing.GroupLayout(jPanelShipping);
        jPanelShipping.setLayout(jPanelShippingLayout);
        jPanelShippingLayout.setHorizontalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelLastNameShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelNumAdressShip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNumStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelStreetShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelStreet2Ship)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreet2Shipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelZipShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelCityShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelCountryShip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCountryShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingLayout.createSequentialGroup()
                        .addComponent(jLabelIdAdressShipp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jTextIdAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelShippingLayout.setVerticalGroup(
            jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingLayout.createSequentialGroup()
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastNameShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumAdressShip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Shipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Ship))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCityShipp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryShip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressShipp))
                .addContainerGap())
        );

        jPanelBilling.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing Adress"));

        jLabelZipBill.setText("Zip Code  :");

        jLabelLastNameBill.setText("Last Name  :");

        jTextZipCodeBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeBillActionPerformed(evt);
            }
        });

        jLabelStreetBill.setText("Street   :");

        jLabelCityBill.setText("City  :");

        jLabelStreet2AdressBill.setText("Steet2");

        jLabelNumAdressBill.setText("jLabel2");

        jLabelCoutryAdressBill.setText("Country");

        jLabelIdAdressBill.setText("IdAdressBill");

        javax.swing.GroupLayout jPanelBillingLayout = new javax.swing.GroupLayout(jPanelBilling);
        jPanelBilling.setLayout(jPanelBillingLayout);
        jPanelBillingLayout.setHorizontalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLastNameBill)
                            .addComponent(jLabelStreetBill)
                            .addComponent(jLabelStreet2AdressBill)
                            .addComponent(jLabelNumAdressBill))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextStreet2Bill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNameReceiverAdressBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNumStreetBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextStreetBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jLabelZipBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jLabelCityBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jLabelCoutryAdressBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCountryBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addComponent(jLabelIdAdressBill)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelBillingLayout.setVerticalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNameReceiverAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastNameBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNumStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumAdressBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetBill)
                    .addComponent(jTextStreetBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2AdressBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCityBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCityBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCoutryAdressBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressBill))
                .addContainerGap())
        );

        jPanelCheckout.setBorder(javax.swing.BorderFactory.createTitledBorder("Checkout"));

        jButtonProceed.setText("Proceed");
        jButtonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProceedActionPerformed(evt);
            }
        });

        jLabelHolderName.setText("Holder name  :");

        jLabelCard.setText("Card number  :");

        jLabelExpDate.setText("Exp Date  :");

        jLabelCCV.setText("CCV  :");

        jLabelTotal.setText("Total  TTC  :");

        jLabelTotalView.setText("99.99 €");

        javax.swing.GroupLayout jPanelCheckoutLayout = new javax.swing.GroupLayout(jPanelCheckout);
        jPanelCheckout.setLayout(jPanelCheckoutLayout);
        jPanelCheckoutLayout.setHorizontalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCard, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                        .addComponent(jLabelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTotalView)
                        .addGap(147, 147, 147)))
                .addContainerGap())
            .addGroup(jPanelCheckoutLayout.createSequentialGroup()
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextOrderDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jTextOrderId, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckoutLayout.createSequentialGroup()
                        .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExpDate)
                            .addComponent(jLabelCCV)
                            .addComponent(jLabelCard)
                            .addComponent(jLabelHolderName))
                        .addGap(34, 34, 34)
                        .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))
                    .addComponent(jButtonProceed, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanelCheckoutLayout.setVerticalGroup(
            jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCheckoutLayout.createSequentialGroup()
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHolderName))
                .addGap(16, 16, 16)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCard)
                    .addComponent(jTextCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExpDate))
                .addGap(18, 18, 18)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCCV)
                    .addComponent(jTextCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTotal)
                    .addComponent(jLabelTotalView)
                    .addComponent(jTextOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanelCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProceed)))
        );

        jComboBoxCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCustomerActionPerformed(evt);
            }
        });

        jLabelComboBoxCustmers.setText("Select a customer");

        jComboBoxCreteriaSearchBook.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Titre" }));

        jLabelComboBoxBooks.setText("Select a Book");

        jComboBoxAdressShipping.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAdressShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdressShippingActionPerformed(evt);
            }
        });

        jComboBoxAdressBilling.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxAdressBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdressBillingActionPerformed(evt);
            }
        });

        jRadioButtonSame.setText("Same as Shipping");
        jRadioButtonSame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSameActionPerformed(evt);
            }
        });

        jLabelDiscount.setText("Discount");

        javax.swing.GroupLayout jPanelNewLayout = new javax.swing.GroupLayout(jPanelNew);
        jPanelNew.setLayout(jPanelNewLayout);
        jPanelNewLayout.setHorizontalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addContainerGap(316, Short.MAX_VALUE)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelNewLayout.createSequentialGroup()
                                .addComponent(jComboBoxCreteriaSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jLabelComboBoxBooks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuantity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabelDiscount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonAddBook))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDeleteLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonClearCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelNewLayout.createSequentialGroup()
                                .addComponent(jLabelComboBoxCustmers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addComponent(jComboBoxAdressShipping, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSame)
                        .addGap(67, 67, 67)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAdressBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanelCartN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNewLayout.setVerticalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantity)
                            .addComponent(jTextQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearCart)
                            .addComponent(jComboBoxBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComboBoxBooks)
                            .addComponent(jLabelDiscount)
                            .addComponent(jTextDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDeleteLine)
                            .addComponent(jButtonAddBook, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxCreteriaSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jPanelCartN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComboBoxCustmers)
                    .addComponent(jComboBoxCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNewLayout.createSequentialGroup()
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxAdressShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSame)
                            .addComponent(jComboBoxAdressBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelBilling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(671, Short.MAX_VALUE))
        );

        jTabbedPaneOrders.addTab("New", jPanelNew);

        add(jTabbedPaneOrders, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchOrdersActionPerformed

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        final String mname = "jButtonAddBookActionPerformed";

        Vector rowCartShopping = new Vector();
        Book book = (Book) jComboBoxBook.getSelectedItem();
        rowCartShopping.add(0, book.getId());
        rowCartShopping.add(1, jTextQuantity.getText());
        rowCartShopping.add(2, book.getUnitCostBook());
        rowCartShopping.add(3, jTextDiscount.getText());

//        jTableShoppingCart.setValueAt( (String) book.getId(),0, 0);
//        jTableShoppingCart.setValueAt(Integer.getInteger(jTextQuantity.getText()),0, 1);
//        jTableShoppingCart.setValueAt((Float)book.getUnitCostBook(),0, 2);
        CodeTVA codeTVA = null;
        try {
            codeTVA = (CodeTVA) otherService.findCodeTVA(book.getCodeTVA().getId());
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CheckException ex) {
            Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
//        jTableShoppingCart.setValueAt((Float)codeTVA.getRateCodeTva(),0, 3);            

        float prixHT = (Integer.parseInt(jTextQuantity.getText())) * book.getUnitCostBook();
        if ((jTextDiscount.getText() != null) && (Integer.parseInt(jTextDiscount.getText()) != 0)) {
            prixHT = prixHT - ((prixHT * Integer.parseInt(jTextDiscount.getText())) / 100);

        }

        float prixTCC = prixHT + (prixHT * codeTVA.getRateCodeTva()) / 100;
//      jTableShoppingCart.setValueAt(prixHT,0, 4);
//      jTableShoppingCart.setValueAt(prixTCC,0, 5);

        rowCartShopping.add(4, Utility.formatFloatToFloatPrecision(codeTVA.getRateCodeTva(), 2));
        rowCartShopping.add(5, Utility.formatFloatToFloatPrecision(prixHT, 2));
        rowCartShopping.add(6, Utility.formatFloatToFloatPrecision(prixTCC, 2));
        cartShopingData.add(rowCartShopping);
        jTableShoppingCart.setModel(initCartShopingTableModel(cartShopingData));
        float totalHT = 0;
        float totalTCC = 0;
        for (Iterator iterator = cartShopingData.iterator(); iterator.hasNext();) {
            Vector vectorCart = (Vector) iterator.next();
            totalHT += (float) vectorCart.elementAt(5);
            totalTCC = totalTCC + (float) vectorCart.elementAt(6);
        }
        jLbelTotalTCCView.setText(String.valueOf(Utility.formatFloatToFloatPrecision(totalTCC, 2)) + " €");
        jLabelTotalHTView.setText(String.valueOf(Utility.formatFloatToFloatPrecision(totalHT, 2)) + " €");

    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jTextZipCodeShippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeShippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeShippActionPerformed

    private void jTextZipCodeBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeBillActionPerformed

    private void jButtonProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProceedActionPerformed
        final String mname = "jButtonProceedActionPerformed";
        final OrderService OrderService = new OrderService();
        final CustomerService customerService = new CustomerService();
        final Orders order;
        try {
            // Sets all the Order data
            order = new Orders();
            // Sets all the order items data
            final Collection orderLines = new ArrayList();
            OrderLine orderLine;

            for (Iterator iterator = cartShopingData.iterator(); iterator.hasNext();) {
                Vector vectorRowCartShoping = (Vector) iterator.next();

                int quantity = Integer.parseInt((String) vectorRowCartShoping.elementAt(1));
                float unitCost = ((Float) vectorRowCartShoping.elementAt(2));
                float rateTVA = ((Float) vectorRowCartShoping.elementAt(3));
                float discount = ((Float) vectorRowCartShoping.elementAt(4));

                orderLine = new OrderLine(new Book((String) vectorRowCartShoping.elementAt(0)),
                        quantity, unitCost, rateTVA);
                orderLine.setDiscountOrderLine(discount);
                orderLines.add(orderLine);

            }

//            for(int i=0; i< this.cartShopingData.size(); i++) { 
//               int quantity = ((Integer) jTableShoppingCart.getModel().getValueAt(i,1)).intValue();
//               float unitCost = (float)(jTableShoppingCart.getModel().getValueAt(i,2));
//               float rateTVA = (float) (jTableShoppingCart.getModel().getValueAt(i,3));
//                
//                orderLine = new OrderLine(new Book( (String) jTableShoppingCart.getModel().getValueAt(i,0)), 
//                            quantity, unitCost, rateTVA );
//                    orderLines.add(orderLine);
//            }
            // Sets all the Order data
            final Customer customer = ((Customer) jComboBoxCustomer.getSelectedItem());
            order.setCustomer(customer);
            order.setDateOrder(java.sql.Date.valueOf(LocalDate.now()));
            order.setPaymentSystemOrder("CB");

            if (jTextIdAdressShipp.getText() == null || jTextIdAdressShipp.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "select a customer", "info message", JOptionPane.INFORMATION_MESSAGE);
            }

            jComboBoxCustomer.setModel(jPanalCustomer.initCustomersComboBoxModel(customer.getListAddressBilling()));
            final Adress adressBilling = ((Adress) jComboBoxAdressShipping.getSelectedItem());

            jComboBoxCustomer.setModel(jPanalCustomer.initCustomersComboBoxModel(customer.getListAddressShipping()));
            final Adress adressShipping = ((Adress) jComboBoxAdressShipping.getSelectedItem());

            order.setAdressShipping(adressShipping);
            order.setAdressBilling(adressBilling);
            order.setListOrderLines(orderLines);
            // Create the order
            final Orders result = OrderService.createOrder(order);
            jTextOrderId.setText(result.getId());
            jTextOrderDate.setText(DateFormat.getDateInstance().format(result.getDateOrder()));

        } catch (Exception e) {            
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
    }//GEN-LAST:event_jButtonProceedActionPerformed


    private void jComboBoxCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCustomerActionPerformed
        Customer customer = (Customer) jComboBoxCustomer.getSelectedItem();

        jComboBoxAdressShipping.setModel(jPanalCustomer.initAdressShipComboBoxModel(
                customer.getListAddressShipping()));

        jComboBoxAdressBilling.setModel(jPanalCustomer.initAdressBillComboBoxModel(
                customer.getListAddressBilling()));
    }//GEN-LAST:event_jComboBoxCustomerActionPerformed

    private void jComboBoxAdressBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdressBillingActionPerformed
        final Adress adressBilling = ((Adress) jComboBoxAdressBilling.getSelectedItem());
        jTextNameReceiverAdressBill.setText(adressBilling.getNameReceiverAdress());
        jTextNumStreetBill.setText(adressBilling.getNumAdress());
        jTextStreetBill.setText(adressBilling.getNameStreetAdress());
        jTextStreet2Bill.setText(adressBilling.getNameStreet2Adress());
        jTextZipCodeBill.setText(adressBilling.getZipcodeAdress());
        jTextCityBill.setText(adressBilling.getCityAdress());
        jTextCountryBill.setText(adressBilling.getCountryAdress());
//      jTextCompany.setText(adress.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressBill.setText(adressBilling.getId());
    }//GEN-LAST:event_jComboBoxAdressBillingActionPerformed

    private void jComboBoxAdressShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdressShippingActionPerformed
        final Adress adressShipping = ((Adress) jComboBoxAdressShipping.getSelectedItem());
        jTextNameReceiverAdressShipp.setText(adressShipping.getNameReceiverAdress());
        jTextNumStreetShipp.setText(adressShipping.getNumAdress());
        jTextStreetShipp.setText(adressShipping.getNameStreetAdress());
        jTextStreet2Shipp.setText(adressShipping.getNameStreet2Adress());
        jTextZipCodeShipp.setText(adressShipping.getZipcodeAdress());
        jTextCityShipp.setText(adressShipping.getCityAdress());
        jTextCountryShipp.setText(adressShipping.getCountryAdress());
//      jTextCompany.setText(adressBilling.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressShipp.setText(adressShipping.getId());

    }//GEN-LAST:event_jComboBoxAdressShippingActionPerformed

    private void jButtonSearchOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchOrdersActionPerformed
        final String mname = "jButtonSearchOrdersActionPerformed";
        Vector vOrders = new Vector();
        Collection orders = new ArrayList();

        if (jComboBoxSearchOrdersBycolumn.getSelectedIndex() == 0) {

            Orders order = null;
            try {
                order = serviceOrder.findOrder(jTextSearchOrders.getText());//              
                orders.add(order);

            } catch (FinderException ex) {
                JOptionPane.showMessageDialog(this, "orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
            } catch (CheckException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

        }

        if (jComboBoxSearchOrdersBycolumn.getSelectedIndex() == 1) {
            Orders order = null;
            try {
                order = serviceOrder.findOrderByNumIternOrder("INTERNALNUMORDER", jTextSearchOrders.getText());//              
                orders.add(order);

            } catch (ObjectNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
            }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

        }

        if (jComboBoxSearchOrdersBycolumn.getSelectedIndex() == 2) {

            try {
                orders = serviceOrder.findOrdersByCustomer("LoginCustomer", jTextSearchOrders.getText());

            } catch (ObjectNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
            }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
        }
        vOrders.addAll(orders);
        jTableOrders.setModel(initOrdersTableModel(vOrders));

    }//GEN-LAST:event_jButtonSearchOrdersActionPerformed

    private void selectLineTableOrdersActionPerformed(ListSelectionEvent evt) {
        final String mname = "selectLineTableOrdersActionPerformed";

        if (evt.getValueIsAdjusting()) {
            return;
        }

        ListSelectionModel lsm = (ListSelectionModel) evt.getSource();

        if (lsm.isSelectionEmpty()) {
            System.out.println("No rows selected");
        } else {
            int selectedRow = lsm.getMinSelectionIndex();
            Orders order = (Orders) Ordersvector.get(selectedRow);
            OrderLinesvector.clear();
            OrderLinesvector.addAll(order.getListOrderLines());
            jTableOrdersLine.setModel(initOrdersLineTableModel(OrderLinesvector));
        }
    }

    private void jRadioButtonSameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSameActionPerformed
        final String mname = "jRadioButtonSameActionPerformed";
        jPanalCustomer.setChampsBillingAdress((Adress) jComboBoxAdressShipping.getSelectedItem());
    }//GEN-LAST:event_jRadioButtonSameActionPerformed

    private void jComboBoxOrderStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrderStatusActionPerformed
        final String mname = "jButtonSetStatusActionPerformed";
        Vector vOrders = new Vector();
        Collection orders = null;
        try {
            if (jComboBoxOrderStatus.getSelectedItem() instanceof InfoStatus) {
                final InfoStatus statusOrders = (InfoStatus) jComboBoxOrderStatus.getSelectedItem();
                orders = serviceOrder.findOrdersByStatus("NAMEINFOSTATUSORDER", statusOrders.getId());
            } else {
                orders = serviceOrder.findOrders();
            }
        if(orders != null) {
        vOrders.addAll(orders);
        jTableOrders.setModel(initOrdersTableModel(vOrders)); 
        }
        
        } catch (ObjectNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
        
        } catch (FinderException ex) {
            JOptionPane.showMessageDialog(this, "orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

    }//GEN-LAST:event_jComboBoxOrderStatusActionPerformed

    // Charger le ComboBox Books 
    public void chargeComboBoxBooks() {
        final String mname = "chargeComboBoxBooks";
        try {
            books = _daoBook.findAll();
            jComboBoxBook.setModel(initBooksComboBoxModel(books));
        } catch (ObjectNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Books id not found", "Warning", JOptionPane.WARNING_MESSAGE);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the book service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
    }

    // Charger le ComboBox Status Orders 
    public void chargeTableOrders() {
        final String mname = "chargeTableOrders";
        OrderService serviceOrder = new OrderService();
        Collection orders = new ArrayList();

        try {
            orders = serviceOrder.findOrders();
            Ordersvector.clear();
            Ordersvector.addAll(orders);
        jTableOrders.setModel(initOrdersTableModel(orders));
        } catch (FinderException ex) {
           JOptionPane.showMessageDialog(this, "Orders id not found", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
        

    }

    // Charger le ComboBox Status Orders 
    public void chargeComboBoxStatusOrders() {
         final String mname = "chargeComboBoxStatusOrders";
        OrderService serviceOrder = new OrderService();
        Collection infoStatus = new ArrayList();
        try {
            infoStatus = serviceOrder.findStatusOrders();
            jComboBoxOrderStatus.setModel(initStatusOrdersComboBoxModel(infoStatus));
        } catch (ObjectNotFoundException ex) {
           JOptionPane.showMessageDialog(this, "Status id not found", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot access the order service for status", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
        

    }

    //Model ComboBox Books
    public DefaultComboBoxModel initBooksComboBoxModel(Collection books) {
        return new DefaultComboBoxModel(initBooksVector(books));
    }

    private Vector initBooksVector(Collection books) {
        final String mname = "initBooksVector";
        Vector v = new Vector();
        v.addAll(books);
        return v;
    }

      //Model ComboBox Orders
    public DefaultComboBoxModel initStatusOrdersComboBoxModel(Collection statusOrders) {
        return new DefaultComboBoxModel(initStatusOrdersVector(statusOrders));
    }

    private Vector initStatusOrdersVector(Collection statusOrders) {
        final String mname = "initStatusOrdersVector";
        Vector v = new Vector();
        v.add("AllOrders");
        v.addAll(statusOrders);
        return v;
    }

    //Model OrdersLine Table
    public DefaultTableModel initOrdersLineTableModel(Collection v) {
        return new DefaultTableModel(initVectorOrdersLineTableData(v), initVectorOrdersLineColumnNamesTable());
    }

    private Vector initVectorOrdersLineTableData(Collection v) {
        Vector rowDada = new Vector();
        for (OrderLine orderLine : (Collection<OrderLine>) v) {
            Vector colData = null;
            colData = new Vector();
            colData.add(orderLine);
            rowDada.add(orderLine.getVector());
        }
        return rowDada;

    }

    private Vector initVectorOrdersLineColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("Num orderLine");
        columnNames.add("Num order");
        columnNames.add("ISBN");
        columnNames.add("Quantity");
        columnNames.add("UnitCost");
        columnNames.add("Discount");
        columnNames.add("Rate TVA");
        columnNames.add("Appreciation");
        return columnNames;
    }

    //Model Orders Table

    public DefaultTableModel initOrdersTableModel(Collection v) {
        return new DefaultTableModel(initVectorOrdersTableData(v), initVectorOrdersColumnNamesTable());
    }

    private Vector initVectorOrdersTableData(Collection v) {
        Vector rowDada = new Vector();
        for (Orders order : (Collection<Orders>) v) {
            Vector colData = null;
            colData = new Vector();
            colData.add(order);
            rowDada.add(order.getVector());
        }
        return rowDada;

    }

    private Vector initVectorOrdersColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("Num order");
        columnNames.add("Num intern order");
        columnNames.add("Date order");
        columnNames.add("LastName customer");
        columnNames.add("FirstName customer");
        columnNames.add("AdressShip customer");
        columnNames.add("Name Shipper");
        columnNames.add("DateShip order");
        columnNames.add("Ip Customer");
        columnNames.add("Status Order");
        return columnNames;
    }

    //Model Cart Shopping Table
    public DefaultTableModel initCartShopingTableModel(Vector v) {
        return new DefaultTableModel(initVectorCartShopingTableData(v), initVectorCartShopingColumnNamesTable());
    }

    private Vector initVectorCartShopingTableData(Vector v) {
        final String mname = "initVectorCartShopingTableData";
//       cartShopingData.addAll(v);
        return cartShopingData;
    }

    private Vector initVectorCartShopingColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("ISBN");
        columnNames.add("QUANTITY");
        columnNames.add("UNIT COST");
        columnNames.add("DISCOUNT");
        columnNames.add("TVA");
        columnNames.add("PRIX HT");
        columnNames.add("PRIX TTC");
        return columnNames;
    }

    protected final transient String _cname = this.getClass().getName();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonClearCart;
    private javax.swing.JButton jButtonDeleteLine;
    private javax.swing.JButton jButtonProceed;
    private javax.swing.JButton jButtonSearchOrders;
    private javax.swing.JButton jButtonUpdateOrder;
    private javax.swing.JComboBox jComboBoxAdressBilling;
    private javax.swing.JComboBox jComboBoxAdressShipping;
    private javax.swing.JComboBox jComboBoxBook;
    private javax.swing.JComboBox jComboBoxCreteriaSearchBook;
    private javax.swing.JComboBox jComboBoxCustomer;
    private javax.swing.JComboBox<String> jComboBoxOrderStatus;
    private javax.swing.JComboBox jComboBoxSearchOrdersBycolumn;
    private javax.swing.JLabel jLabelCCV;
    private javax.swing.JLabel jLabelCard;
    private javax.swing.JLabel jLabelCityBill;
    private javax.swing.JLabel jLabelCityShipp;
    private javax.swing.JLabel jLabelComboBoxBooks;
    private javax.swing.JLabel jLabelComboBoxCustmers;
    private javax.swing.JLabel jLabelCountryShip;
    private javax.swing.JLabel jLabelCoutryAdressBill;
    private javax.swing.JLabel jLabelDiscount;
    private javax.swing.JLabel jLabelExpDate;
    private javax.swing.JLabel jLabelHolderName;
    private javax.swing.JLabel jLabelIdAdressBill;
    private javax.swing.JLabel jLabelIdAdressShipp;
    private javax.swing.JLabel jLabelLastNameBill;
    private javax.swing.JLabel jLabelLastNameShipp;
    private javax.swing.JLabel jLabelNumAdressBill;
    private javax.swing.JLabel jLabelNumAdressShip;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelStreet2AdressBill;
    private javax.swing.JLabel jLabelStreet2Ship;
    private javax.swing.JLabel jLabelStreetBill;
    private javax.swing.JLabel jLabelStreetShipp;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalHT;
    private javax.swing.JLabel jLabelTotalHTView;
    private javax.swing.JLabel jLabelTotalTCC;
    private javax.swing.JLabel jLabelTotalView;
    private javax.swing.JLabel jLabelZipBill;
    private javax.swing.JLabel jLabelZipShipp;
    private javax.swing.JLabel jLbelTotalTCCView;
    private javax.swing.JPanel jPanelBilling;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelCartN;
    private javax.swing.JPanel jPanelCheckout;
    private javax.swing.JPanel jPanelManage;
    private javax.swing.JPanel jPanelNew;
    private javax.swing.JPanel jPanelOrdersWaiting;
    private javax.swing.JPanel jPanelSearchOrder;
    private javax.swing.JPanel jPanelShipping;
    private javax.swing.JRadioButton jRadioButtonSame;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPaneCart;
    private javax.swing.JScrollPane jScrollPaneOrdersWaiting;
    private javax.swing.JTabbedPane jTabbedPaneOrders;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JTable jTableOrdersLine;
    private javax.swing.JTable jTableShoppingCart;
    private javax.swing.JTextField jTextAddBook;
    private javax.swing.JTextField jTextCCV;
    private javax.swing.JTextField jTextCard;
    private javax.swing.JTextField jTextCityBill;
    private javax.swing.JTextField jTextCityShipp;
    private javax.swing.JTextField jTextCountryBill;
    private javax.swing.JTextField jTextCountryShipp;
    private javax.swing.JTextField jTextDiscount;
    private javax.swing.JTextField jTextExpDate;
    private javax.swing.JTextField jTextHolderName;
    private javax.swing.JTextField jTextIdAdressBill;
    private javax.swing.JTextField jTextIdAdressShipp;
    private javax.swing.JTextField jTextNameReceiverAdressBill;
    private javax.swing.JTextField jTextNameReceiverAdressShipp;
    private javax.swing.JTextField jTextNumStreetBill;
    private javax.swing.JTextField jTextNumStreetShipp;
    private javax.swing.JTextField jTextOrderDate;
    private javax.swing.JTextField jTextOrderId;
    private javax.swing.JTextField jTextQuantity;
    private javax.swing.JTextField jTextSearchOrders;
    private javax.swing.JTextField jTextStreet2Bill;
    private javax.swing.JTextField jTextStreet2Shipp;
    private javax.swing.JTextField jTextStreetBill;
    private javax.swing.JTextField jTextStreetShipp;
    private javax.swing.JTextField jTextZipCodeBill;
    private javax.swing.JTextField jTextZipCodeShipp;
    // End of variables declaration//GEN-END:variables
}
