/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

import com.cdi.g3.common.exception.CheckException;
import com.cdi.g3.common.exception.FinderException;
import com.cdi.g3.common.exception.ObjectNotFoundException;
import com.cdi.g3.common.logging.Trace;
import com.cdi.g3.server.domain.customers.Adress;
import com.cdi.g3.server.domain.customers.Customer;
import com.cdi.g3.server.domain.orders.InfoStatus;
import com.cdi.g3.server.domain.orders.Orders;
import com.cdi.g3.server.service.customers.AdressService;
import com.cdi.g3.server.service.customers.CustomerService;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Apotheas
 */
public class JPanelFormCustomers extends javax.swing.JPanel {

    //public class JPanelFormCustomers extends  JDesktopPane{
    CustomerService serviceCustomer = new CustomerService();
    DefaultTableModel myModelAdressShip = new DefaultTableModel();
    DefaultTableModel myModelAdressBill = new DefaultTableModel();
    DefaultTableModel myModelCustomers = new DefaultTableModel();
    Vector adressBillList = new Vector();
    Vector adressShipList = new Vector();
    Vector customersVector = new Vector();
    Vector statusCustomersVector = new Vector();

    DateFormat df = new SimpleDateFormat("dd-MM-YYYY");

    public JDialog getjDialogAddAdressBill() {
        return jDialogAddAdressShip;
    }

    public DefaultTableModel getMyModelAdressBill() {
        return myModelAdressBill;
    }

    public JDialog getjDialogAddAdressShip() {
        return jDialogAddAdressBill;
    }

    /**
     * Creates new form Accounts
     */
    public JPanelFormCustomers() {
        initComponents();
        jTableCustomers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

//        jTableCustomers1.setAutoCreateRowSorter(true);
        jTableCustomers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent evt) {
                selectLineTableCustomerActionPerformed(evt);
            }
        });

        jPanelShippingAdress1.setVisible(false);
        jPanelBillingAdress1.setVisible(false);
        jTextIdAdressBill1.setEditable(true);
        jTextIdAdressShipp1.setEditable(true);
        jTextIdAdressBill1.setEditable(true);
        jPanelCustomer.setVisible(false);
        jPanelShippingAdress1.setVisible(false);
        jPanelBillingAdress1.setVisible(false);

        chargeComboBoxCustomers();
        chargeComboBoxStatusCustomers();
        jComboBoxStatus.setModel(initStatusCustomersComboBoxModel(statusCustomersVector));
        jTableCustomers.setModel(initCustomersTableModel(customersVector));

//        jComboBoxCustomers.setSelectedIndex(-1);
//        jComboBoxShip.setModel(initComboAdressShipModel(adressShipList));
//        jComboBoxBill.setModel(initComboAdressBillModel(adressBillList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddAdressShip = new javax.swing.JDialog();
        jPanelShippingAdress1 = new javax.swing.JPanel();
        jLabeNameReceiverAdressShipp1 = new javax.swing.JLabel();
        jTextNameReceiverAdressShipp1 = new javax.swing.JTextField();
        jLabelStreetShipp1 = new javax.swing.JLabel();
        jLabelZipCodeShipp1 = new javax.swing.JLabel();
        jLabelCityShipp1 = new javax.swing.JLabel();
        jTextStreetShipp1 = new javax.swing.JTextField();
        jTextCityShipp1 = new javax.swing.JTextField();
        jTextZipCodeShipp1 = new javax.swing.JTextField();
        jTextNumStreetShipp1 = new javax.swing.JTextField();
        jLabelNumStreetShipp1 = new javax.swing.JLabel();
        jTextStreet2Shipp1 = new javax.swing.JTextField();
        jLabelStreet2Shipp1 = new javax.swing.JLabel();
        jTextCountryShipp1 = new javax.swing.JTextField();
        jLabelCountryShipp1 = new javax.swing.JLabel();
        jTextIdAdressShipp1 = new javax.swing.JTextField();
        jLabelIdAdressShipp1 = new javax.swing.JLabel();
        jButtonSendAdressShip = new javax.swing.JButton();
        jDialogAddAdressBill = new javax.swing.JDialog();
        jPanelBillingAdress1 = new javax.swing.JPanel();
        jLabelZipCodeBill1 = new javax.swing.JLabel();
        jTextCityBill1 = new javax.swing.JTextField();
        jLabelNameReceiverAdressBill1 = new javax.swing.JLabel();
        jTextIdAdressBill1 = new javax.swing.JTextField();
        jTextNameReceiverAdressBill1 = new javax.swing.JTextField();
        jTextZipCodeBill1 = new javax.swing.JTextField();
        jLabelStreetBill1 = new javax.swing.JLabel();
        jLabelIdAdressBill1 = new javax.swing.JLabel();
        jTextStreetBill1 = new javax.swing.JTextField();
        jLabelCityBill1 = new javax.swing.JLabel();
        jTextNumStreetBill1 = new javax.swing.JTextField();
        jLabelNumStreetBill1 = new javax.swing.JLabel();
        jTextCountryBill1 = new javax.swing.JTextField();
        jLabelCountryBill1 = new javax.swing.JLabel();
        jTextStreet2Bill1 = new javax.swing.JTextField();
        jLabelStreet2Bill1 = new javax.swing.JLabel();
        jButtonSendAdressBill = new javax.swing.JButton();
        jPanelAccounts = new javax.swing.JPanel();
        jTabbedPaneManageAccount = new javax.swing.JTabbedPane();
        jScrollPaneTree1 = new javax.swing.JScrollPane();
        jTreeCustomers = new javax.swing.JTree();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxCustomers = new javax.swing.JComboBox();
        jComboBoxSearchCustomer = new javax.swing.JComboBox();
        jLabelSearch1 = new javax.swing.JLabel();
        jTextSearchCustomer = new javax.swing.JTextField();
        jButtonSearchCustomer = new javax.swing.JButton();
        AddCustomer = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jPanelCustomer = new javax.swing.JPanel();
        jComboBoxStatus = new javax.swing.JComboBox<String>();
        jLabelStatus1 = new javax.swing.JLabel();
        jTextPassword = new javax.swing.JTextField();
        jLabelPassword1 = new javax.swing.JLabel();
        jTextCompany = new javax.swing.JTextField();
        jLabelCompany1 = new javax.swing.JLabel();
        jLabelLogin1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jTextLogin = new javax.swing.JTextField();
        jLabelFirstName1 = new javax.swing.JLabel();
        jTextLastName = new javax.swing.JTextField();
        jLabelLastName1 = new javax.swing.JLabel();
        jButtonCreateCustomer = new javax.swing.JButton();
        jComboBoxShip = new javax.swing.JComboBox();
        jComboBoxBill = new javax.swing.JComboBox();
        jButtonAdressShipping = new javax.swing.JButton();
        jButtonAdressBilling = new javax.swing.JButton();
        jPanelAdress = new javax.swing.JPanel();
        jLabeNameReceiverAdressShipp2 = new javax.swing.JLabel();
        jTextNameReceiverAdressShipp = new javax.swing.JTextField();
        jLabelStreetShipp2 = new javax.swing.JLabel();
        jLabelZipCodeShipp2 = new javax.swing.JLabel();
        jLabelCityShipp2 = new javax.swing.JLabel();
        jTextStreetShipp = new javax.swing.JTextField();
        jTextCityShipp = new javax.swing.JTextField();
        jTextZipCodeShipp = new javax.swing.JTextField();
        jTextNumStreetShipp = new javax.swing.JTextField();
        jLabelNumStreetShipp2 = new javax.swing.JLabel();
        jTextStreet2Shipp = new javax.swing.JTextField();
        jLabelStreet2Shipp2 = new javax.swing.JLabel();
        jTextCountryShipp = new javax.swing.JTextField();
        jLabelCountryShipp2 = new javax.swing.JLabel();
        jLabelIdAdressShipp2 = new javax.swing.JLabel();
        jButtonCreateAdressBill = new javax.swing.JButton();
        jButtonCreateAdressShip = new javax.swing.JButton();
        jButtonUpdateAdressBill = new javax.swing.JButton();
        jButtonUptateAdressShip = new javax.swing.JButton();
        jTextIdAdressShipp = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextFirstName = new javax.swing.JTextField();
        jButtonUpdateCustomer = new javax.swing.JButton();

        jPanelShippingAdress1.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping adress"));

        jLabeNameReceiverAdressShipp1.setText("Last Name  :");

        jLabelStreetShipp1.setText("Street   :");

        jLabelZipCodeShipp1.setText("Zip Code  :");

        jLabelCityShipp1.setText("City  :");

        jTextZipCodeShipp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeShipp1ActionPerformed(evt);
            }
        });

        jLabelNumStreetShipp1.setText("Num Street   :");

        jLabelStreet2Shipp1.setText("Street2");

        jLabelCountryShipp1.setText("Country");

        jLabelIdAdressShipp1.setText("Id Adress Ship");

        jButtonSendAdressShip.setText("Send ");
        jButtonSendAdressShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendAdressShipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShippingAdress1Layout = new javax.swing.GroupLayout(jPanelShippingAdress1);
        jPanelShippingAdress1.setLayout(jPanelShippingAdress1Layout);
        jPanelShippingAdress1Layout.setHorizontalGroup(
            jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabeNameReceiverAdressShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelNumStreetShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNumStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreetShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelZipCodeShipp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStreet2Shipp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextStreet2Shipp1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextZipCodeShipp1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCityShipp1)
                            .addComponent(jLabelCountryShipp1)
                            .addComponent(jLabelIdAdressShipp1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIdAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextCountryShipp1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jTextCityShipp1))))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSendAdressShip))))
        );
        jPanelShippingAdress1Layout.setVerticalGroup(
            jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumStreetShipp1)
                    .addComponent(jTextNumStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetShipp1)
                    .addComponent(jTextStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Shipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Shipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipCodeShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCityShipp1)
                    .addComponent(jTextCityShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSendAdressShip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogAddAdressShip.getContentPane().add(jPanelShippingAdress1, java.awt.BorderLayout.CENTER);

        jPanelBillingAdress1.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing adress"));

        jLabelZipCodeBill1.setText("Zip Code  :");

        jLabelNameReceiverAdressBill1.setText("Last Name  :");

        jTextZipCodeBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeBill1ActionPerformed(evt);
            }
        });

        jLabelStreetBill1.setText("Street   :");

        jLabelIdAdressBill1.setText("Id Adress Bill");

        jLabelCityBill1.setText("City  :");

        jLabelNumStreetBill1.setText("Num Street   :");

        jLabelCountryBill1.setText("Country");

        jLabelStreet2Bill1.setText("Street2");

        jButtonSendAdressBill.setText("send");
        jButtonSendAdressBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendAdressBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBillingAdress1Layout = new javax.swing.GroupLayout(jPanelBillingAdress1);
        jPanelBillingAdress1.setLayout(jPanelBillingAdress1Layout);
        jPanelBillingAdress1Layout.setHorizontalGroup(
            jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNameReceiverAdressBill1)
                            .addComponent(jLabelNumStreetBill1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNumStreetBill1)
                            .addComponent(jTextNameReceiverAdressBill1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdAdressBill1)
                            .addComponent(jLabelCountryBill1)
                            .addComponent(jLabelCityBill1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCountryBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCityBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdAdressBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreetBill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreet2Bill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreet2Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSendAdressBill))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelZipCodeBill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBillingAdress1Layout.setVerticalGroup(
            jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameReceiverAdressBill1)
                    .addComponent(jTextNameReceiverAdressBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNumStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumStreetBill1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetBill1))
                .addGap(9, 9, 9)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Bill1))
                .addGap(7, 7, 7)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipCodeBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCityBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCityBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSendAdressBill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogAddAdressBill.getContentPane().add(jPanelBillingAdress1, java.awt.BorderLayout.CENTER);

        setLayout(new java.awt.BorderLayout());

        jTreeCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder("Profils"));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Status");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Active");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BlackListed");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeCustomers.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeCustomersMouseClicked(evt);
            }
        });
        jScrollPaneTree1.setViewportView(jTreeCustomers);

        jTabbedPaneManageAccount.addTab("Consult", jScrollPaneTree1);

        jComboBoxCustomers.setModel(initAdressBillComboBoxModel(customersVector));
        jComboBoxCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCustomersMouseEntered(evt);
            }
        });
        jComboBoxCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCustomersActionPerformed(evt);
            }
        });

        jComboBoxSearchCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pseudo", "Email" }));

        jLabelSearch1.setText("search by pseudo/email  :");

        jButtonSearchCustomer.setText("search");
        jButtonSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCustomerActionPerformed(evt);
            }
        });

        AddCustomer.setText("AddCustomer");
        AddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerActionPerformed(evt);
            }
        });

        jTableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCustomers);

        jPanelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(153, 153, 255))); // NOI18N

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive", "BlackList" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        jLabelStatus1.setText("Status  :");

        jTextPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPasswordActionPerformed(evt);
            }
        });

        jLabelPassword1.setText("Password  :");

        jTextCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompanyActionPerformed(evt);
            }
        });

        jLabelCompany1.setText("Company  : ");

        jLabelLogin1.setText("Login  :");

        jLabelEmail1.setText("Email  :");

        jTextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLoginActionPerformed(evt);
            }
        });

        jLabelFirstName1.setText("First name :");

        jLabelLastName1.setText("Last  name :");

        jButtonCreateCustomer.setText("Create Customer");
        jButtonCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateCustomerActionPerformed(evt);
            }
        });

        jComboBoxShip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShipActionPerformed(evt);
            }
        });

        jComboBoxBill.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBillActionPerformed(evt);
            }
        });

        jButtonAdressShipping.setText("Add AdressChipping");
        jButtonAdressShipping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdressShippingActionPerformed(evt);
            }
        });

        jButtonAdressBilling.setText("Add AdressBilling");
        jButtonAdressBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdressBillingActionPerformed(evt);
            }
        });

        jPanelAdress.setBorder(javax.swing.BorderFactory.createTitledBorder("Adress"));

        jLabeNameReceiverAdressShipp2.setText("Last Name  :");

        jLabelStreetShipp2.setText("Street   :");

        jLabelZipCodeShipp2.setText("Zip Code  :");

        jLabelCityShipp2.setText("City  :");

        jTextZipCodeShipp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeShippActionPerformed(evt);
            }
        });

        jLabelNumStreetShipp2.setText("Num Street   :");

        jLabelStreet2Shipp2.setText("Street2");

        jLabelCountryShipp2.setText("Country");

        jLabelIdAdressShipp2.setText("Id Adress Ship");

        jButtonCreateAdressBill.setText("Create Adress Bill");
        jButtonCreateAdressBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAdressBillActionPerformed(evt);
            }
        });

        jButtonCreateAdressShip.setText("Create Adress Ship");
        jButtonCreateAdressShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateAdressShipActionPerformed(evt);
            }
        });

        jButtonUpdateAdressBill.setText("Uptade Adress Bill");

        jButtonUptateAdressShip.setText("Update Adress Ship");

        javax.swing.GroupLayout jPanelAdressLayout = new javax.swing.GroupLayout(jPanelAdress);
        jPanelAdress.setLayout(jPanelAdressLayout);
        jPanelAdressLayout.setHorizontalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdressLayout.createSequentialGroup()
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCityShipp2)
                            .addComponent(jLabelCountryShipp2)
                            .addComponent(jLabelIdAdressShipp2))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCountryShipp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextCityShipp)
                            .addComponent(jTextIdAdressShipp)))
                    .addGroup(jPanelAdressLayout.createSequentialGroup()
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeNameReceiverAdressShipp2)
                            .addComponent(jLabelNumStreetShipp2)
                            .addComponent(jLabelStreetShipp2)
                            .addComponent(jLabelStreet2Shipp2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelZipCodeShipp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextStreet2Shipp, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jTextStreetShipp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNumStreetShipp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextZipCodeShipp))))
                .addContainerGap())
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonUpdateAdressBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUptateAdressShip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCreateAdressShip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreateAdressBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelAdressLayout.setVerticalGroup(
            jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdressLayout.createSequentialGroup()
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNameReceiverAdressShipp2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNameReceiverAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumStreetShipp2)
                    .addComponent(jTextNumStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetShipp2)
                    .addComponent(jTextStreetShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Shipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Shipp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelZipCodeShipp2)
                    .addComponent(jTextZipCodeShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCityShipp2)
                    .addComponent(jTextCityShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryShipp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdAdressShipp2)
                    .addComponent(jTextIdAdressShipp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreateAdressBill)
                    .addComponent(jButtonUpdateAdressBill, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreateAdressShip)
                    .addComponent(jButtonUptateAdressShip))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jButtonUpdateCustomer.setText("Update Customer");

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLastName1)
                            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstName1)
                                    .addComponent(jLabelLogin1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                                .addComponent(jButtonAdressBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxBill, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                                .addComponent(jButtonAdressShipping)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxShip, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabelPassword1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabelStatus1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                                .addComponent(jLabelCompany1)
                                .addGap(33, 33, 33)
                                .addComponent(jTextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin1)
                    .addComponent(jLabelStatus1)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword1)
                    .addComponent(jLabelEmail1)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCompany1)
                    .addComponent(jLabelFirstName1)
                    .addComponent(jTextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAdressShipping))
                    .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextLastName)
                        .addComponent(jLabelLastName1)))
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCreateCustomer))
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdressBilling)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateCustomer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addComponent(jPanelAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jTextSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearchCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddCustomer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSearch1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchCustomer)
                    .addComponent(AddCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPaneManageAccount.addTab("Manage", jDesktopPane1);

        javax.swing.GroupLayout jPanelAccountsLayout = new javax.swing.GroupLayout(jPanelAccounts);
        jPanelAccounts.setLayout(jPanelAccountsLayout);
        jPanelAccountsLayout.setHorizontalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addComponent(jTabbedPaneManageAccount)
                .addContainerGap())
        );
        jPanelAccountsLayout.setVerticalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addComponent(jTabbedPaneManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        add(jPanelAccounts, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void jTextZipCodeShipp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeShipp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeShipp1ActionPerformed

    private void jTextZipCodeBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeBill1ActionPerformed

    private void jButtonSendAdressBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendAdressBillActionPerformed

        final String mname = "jButtonCreateActionPerformed";
        AdressService serviceAdress = new AdressService();
        Adress adressBlling = new Adress();
        try {
            // Asks if we want to remove the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create adressBlling ", "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            adressBlling.setNameReceiverAdress(jTextNameReceiverAdressBill1.getText());
            adressBlling.setNumAdress(jTextNumStreetBill1.getText());
            adressBlling.setNameStreetAdress(jTextStreetBill1.getText());
            adressBlling.setNameStreet2Adress(jTextStreet2Bill1.getText());
            adressBlling.setZipcodeAdress(jTextZipCodeBill1.getText());
            adressBlling.setCityAdress(jTextCityBill1.getText());
            adressBlling.setCountryAdress(jTextCountryBill1.getText());
            adressBlling.setCustomerBillAdress(new Customer(jTextLogin.getText()));
            adressBlling = serviceAdress.createAdress(adressBlling);
            adressBillList.add(adressBlling);

            // Create the customer
            JOptionPane.showMessageDialog(this, "adressBlling number " + adressBlling.getId()
                    + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);

//            jButtonCreateAdressShip1.setVisible(false);
            jComboBoxBill.setModel(initAdressShipComboBoxModel(adressBillList));

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the adress service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }


    }//GEN-LAST:event_jButtonSendAdressBillActionPerformed

    private void jButtonSendAdressShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendAdressShipActionPerformed
        final String mname = "jButtonCreateActionPerformed";
        AdressService serviceAdress = new AdressService();
        Adress adressShipping = new Adress();
        try {
            // Asks if we want to remove the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create adressShipping "
                    + adressShipping.getId(), "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            adressShipping.setNameReceiverAdress(jTextNameReceiverAdressShipp1.getText());
            adressShipping.setNumAdress(jTextNumStreetShipp1.getText());
            adressShipping.setNameStreetAdress(jTextStreetShipp1.getText());
            adressShipping.setNameStreet2Adress(jTextStreet2Shipp1.getText());
            adressShipping.setZipcodeAdress(jTextZipCodeShipp1.getText());
            adressShipping.setCityAdress(jTextCityShipp1.getText());
            adressShipping.setCountryAdress(jTextCountryShipp1.getText());
            adressShipping.setCustomerShipAdress(new Customer(jTextLogin.getText()));
            adressShipping = serviceAdress.createAdress(adressShipping);

            adressShipList.add(adressShipping);

            // Create the customer
            JOptionPane.showMessageDialog(this, "adressShipping number " + adressShipping.getId()
                    + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxShip.setModel(initAdressShipComboBoxModel(adressShipList));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }


    }//GEN-LAST:event_jButtonSendAdressShipActionPerformed
    private void selectLineTableCustomerActionPerformed(ListSelectionEvent evt) {

        if (evt.getValueIsAdjusting()) {
            return;
        }

        ListSelectionModel lsm = (ListSelectionModel) evt.getSource();

        if (lsm.isSelectionEmpty()) {
            System.out.println("No rows selected");
        } else {
            int selectedRow = lsm.getMinSelectionIndex();
            Customer customer = (Customer) customersVector.get(selectedRow);
            jPanelCustomer.setVisible(true);
            jTextEmail.setText(customer.getEmailCustomer());
            jTextFirstName.setText(customer.getFirstNameCustomer());
            jTextLogin.setText(customer.getId());
            jTextLastName.setText(customer.getLastNameCustomer());
            jTextCompany.setText(customer.getNameCompanyCustomer());
            jComboBoxStatus.setSelectedIndex(customer.getStatusCustomer());

            Adress adressShipping = new Adress();
            adressShipList.clear();
            adressBillList.clear();
            adressShipList.addAll(customer.getListAddressShipping());
            adressBillList.addAll(customer.getListAddressBilling());
            jComboBoxShip.setModel(initAdressShipComboBoxModel(adressShipList));
            jComboBoxBill.setModel(initAdressShipComboBoxModel(adressBillList));

            if (customer.getListAddressShipping().size() > 0) {
                jPanelAdress.setVisible(true);
                jButtonCreateAdressBill.setVisible(false);
                jButtonCreateAdressShip.setVisible(false);
                jButtonUpdateAdressBill.setVisible(false);
                setTextFieldAdress((Adress) adressShipList.elementAt(0));
                jButtonCreateCustomer.setVisible(false);
                jButtonUpdateCustomer.setVisible(true);
            return;
            
            } else if (customer.getListAddressBilling().size() > 0) {
                jPanelAdress.setVisible(true);
                jButtonCreateAdressBill.setVisible(false);
                jButtonCreateAdressShip.setVisible(false);
                jButtonUptateAdressShip.setVisible(false);
                setTextFieldAdress((Adress) adressBillList.elementAt(0));
                jButtonCreateCustomer.setVisible(false);
                jButtonUpdateCustomer.setVisible(true);
                return;
            }
            
            else {
                jPanelAdress.setVisible(false);
                jButtonCreateCustomer.setVisible(true);
                jButtonUpdateCustomer.setVisible(false);
                
            }
            

        }
    }


    private void AddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerActionPerformed
        jPanelCustomer.setVisible(true);
        jPanelAdress.setVisible(false);
        clearCustomer();
        jButtonCreateCustomer.setVisible(true);
        jButtonUpdateCustomer.setVisible(false);

        jComboBoxShip.setModel(initAdressShipComboBoxModel(adressShipList));
        jComboBoxBill.setModel(initAdressShipComboBoxModel(adressBillList));
    }//GEN-LAST:event_AddCustomerActionPerformed

    private void jButtonSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCustomerActionPerformed
        final String mname = "jButtonSearchOrdersActionPerformed";
        Vector vOrders = new Vector();
        Collection orders = new ArrayList();

        if (jComboBoxSearchCustomer.getSelectedIndex() == 0) {

            Customer customer = null;
            try {
                customer = serviceCustomer.findCustomer(jTextSearchCustomer.getText());//
                orders.add(customer);

            } catch (FinderException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CheckException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (jComboBoxSearchCustomer.getSelectedIndex() == 1) {
            Customer customer = null;
            try {
                customer = serviceCustomer.findCustomerByEmail("Email", jTextSearchCustomer.getText());//
                orders.add(customer);

            } catch (ObjectNotFoundException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        vOrders.addAll(orders);
        jTableCustomers.setModel(initCustomersTableModel(vOrders));
    }//GEN-LAST:event_jButtonSearchCustomerActionPerformed

    private void jComboBoxCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCustomersActionPerformed
        customersVector.clear();
        customersVector.add((Customer) jComboBoxCustomers.getSelectedItem());
        jTableCustomers.setModel(initCustomersTableModel(customersVector));
    }//GEN-LAST:event_jComboBoxCustomersActionPerformed

    private void jComboBoxCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCustomersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCustomersMouseEntered

    private void jButtonAdressBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdressBillingActionPerformed
        jPanelAdress.setVisible(true);

        //  Jdialog
        clearBillingAdress();
        JDialog jDialogAdAdressBill = getjDialogAddAdressBill();
        jDialogAddAdressBill.setVisible(true);
        jPanelBillingAdress1.setVisible(true);
    }//GEN-LAST:event_jButtonAdressBillingActionPerformed

    private void jButtonAdressShippingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdressShippingActionPerformed
        jPanelAdress.setVisible(true);

        //  Jdialog
        clearShippingAdress();
        JDialog jDialogAddAdressShip = getjDialogAddAdressShip();
        jDialogAddAdressShip.setVisible(true);
        jPanelShippingAdress1.setVisible(true);
    }//GEN-LAST:event_jButtonAdressShippingActionPerformed

    private void jComboBoxBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBillActionPerformed

    private void jComboBoxShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxShipActionPerformed

    private void jButtonCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateCustomerActionPerformed
        final String mname = "jButtonCreateActionPerformed";
        CustomerService serviceCustomer = new CustomerService();
        Customer customer = null;
        try {
            customer = new Customer(jTextLogin.getText(), jTextFirstName.getText(), jTextLastName.getText(), jTextEmail.getText(), jTextPassword.getText());

            // Asks if we want to create the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create customer "
                    + customer.getId() + " " + customer.getLastNameCustomer(), "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            customer = serviceCustomer.createCustomer(customer);
            customersVector.add(customer);
            jTableCustomers.setModel(initCustomersTableModel(customersVector));
            JOptionPane.showMessageDialog(this, "Customer number " + customer.getId()
                    + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

    }//GEN-LAST:event_jButtonCreateCustomerActionPerformed

    private void jTextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLoginActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jTextCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompanyActionPerformed

    private void jTextPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPasswordActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jTreeCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeCustomersMouseClicked
        final String mname = "jTreeCustomersMouseClicked";
        CustomerService serviceCustomer = new CustomerService();
        try {
            Collection customers = serviceCustomer.findCustomers();
            jTreeCustomers.setModel(initCustomersTreeModel(customers));
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTreeCustomersMouseClicked

    private void jTextZipCodeShippActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeShippActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeShippActionPerformed

    private void jButtonCreateAdressBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAdressBillActionPerformed

        final String mname = "jButtonCreateActionPerformed";
        AdressService serviceAdress = new AdressService();
        Adress adressShipping = new Adress();
        try {
            // Asks if we want to remove the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create adressShipping "
                    + adressShipping.getId(), "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            adressShipping = setChampsAdress(adressShipping);

            adressShipping = serviceAdress.createAdress(adressShipping);
            adressShipList.add(adressShipping);
            // Create the customer
            JOptionPane.showMessageDialog(this, "adressShipping number " + adressShipping.getId()
                    + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxShip.setModel(initAdressShipComboBoxModel(adressShipList));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreateAdressBillActionPerformed

    private void jButtonCreateAdressShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateAdressShipActionPerformed


    }//GEN-LAST:event_jButtonCreateAdressShipActionPerformed

    public void setChampsBillingAdress(Adress adress) {
        jTextNameReceiverAdressBill1.setText(adress.getNameReceiverAdress());
        jTextNumStreetBill1.setText(adress.getNumAdress());
        jTextStreetBill1.setText(adress.getNameStreetAdress());
        jTextStreet2Bill1.setText(adress.getNameStreet2Adress());
        jTextZipCodeBill1.setText(adress.getZipcodeAdress());
        jTextCityBill1.setText(adress.getCityAdress());
        jTextCountryBill1.setText(adress.getCountryAdress());
        jTextCompany.setText(adress.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressBill1.setText(adress.getId());

    }

    public void clearBillingAdress() {
        jTextNameReceiverAdressBill1.setText("");
        jTextNumStreetBill1.setText("");
        jTextStreetBill1.setText("");
        jTextStreet2Bill1.setText("");
        jTextZipCodeBill1.setText("");
        jTextCityBill1.setText("");
        jTextCountryBill1.setText("");
        jTextCompany.setText("");
        jTextIdAdressBill1.setText("");

    }

    public void clearCustomer() {
        jTextLogin.setText("");
        jTextEmail.setText("");
        jTextFirstName.setText("");
        jTextLastName.setText("");
        jTextPassword.setText("");
        jTextCompany.setText("");
        adressShipList.clear();
        adressBillList.clear();

    }

    public Adress setChampsAdress(Adress adress) {
        adress.setNameReceiverAdress(jTextNameReceiverAdressShipp1.getText());
        adress.setNumAdress(jTextNumStreetShipp1.getText());
        adress.setNameStreetAdress(jTextStreetShipp1.getText());
        adress.setNameStreet2Adress(jTextStreet2Shipp1.getText());
        adress.setZipcodeAdress(jTextZipCodeShipp1.getText());
        adress.setCityAdress(jTextCityShipp1.getText());
        adress.setCountryAdress(jTextCountryShipp1.getText());
        adress.setCustomerShipAdress(new Customer(jTextLogin.getText()));
        return adress;

    }

    public void setTextFieldAdress(Adress adress) {
        jTextNameReceiverAdressShipp.setText(adress.getNameReceiverAdress());
        jTextNumStreetShipp.setText(adress.getNumAdress());
        jTextStreetShipp.setText(adress.getNameStreetAdress());
        jTextStreet2Shipp.setText(adress.getNameStreet2Adress());
        jTextZipCodeShipp.setText(adress.getZipcodeAdress());
        jTextCityShipp.setText(adress.getCityAdress());
        jTextCountryShipp.setText(adress.getCountryAdress());
        jTextIdAdressShipp.setText(adress.getId());

    }

    public void setChampsShippingAdress(Adress adress) {
        jTextNameReceiverAdressShipp1.setText(adress.getNameReceiverAdress());
        jTextNumStreetShipp1.setText(adress.getNumAdress());
        jTextStreetShipp1.setText(adress.getNameStreetAdress());
        jTextStreet2Shipp1.setText(adress.getNameStreet2Adress());
        jTextZipCodeShipp1.setText(adress.getZipcodeAdress());
        jTextCityShipp1.setText(adress.getCityAdress());
        jTextCountryShipp1.setText(adress.getCountryAdress());
        jTextCompany.setText(adress.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressShipp1.setText(adress.getId());

    }

    public void clearShippingAdress() {
        jTextNameReceiverAdressShipp1.setText("");
        jTextNumStreetShipp1.setText("");
        jTextStreetShipp1.setText("");
        jTextStreet2Bill1.setText("");
        jTextZipCodeShipp1.setText("");
        jTextCityShipp1.setText("");
        jTextCountryShipp1.setText("");
        jTextCompany.setText("");
        jTextIdAdressShipp1.setText("");

    }

    public DefaultComboBoxModel initCustomersComboBoxModel(Collection customers) {
        return new DefaultComboBoxModel(initCustomersVector(customers));
    }

    private Vector initCustomersVector(Collection customers) {
        final String mname = "initCustomersVector";
        Vector v = new Vector();
        v.addAll(customers);
        return v;
    }

    public DefaultComboBoxModel initAdressShipComboBoxModel(Collection adressesChip) {
        return new DefaultComboBoxModel(initAdressShipVector(adressesChip));
    }

    private Vector initAdressShipVector(Collection adressesChip) {
        final String mname = "initAdressChipVector";
        Vector v = new Vector();
        v.addAll(adressesChip);
        return v;
    }

    public DefaultComboBoxModel initAdressBillComboBoxModel(Collection adressesBill) {
        return new DefaultComboBoxModel(initAdressBillVector(adressesBill));
    }

    private Vector initAdressBillVector(Collection adressesBill) {
        final String mname = "initAdressChipVector";
        Vector v = new Vector();
        v.addAll(adressesBill);
        return v;
    }

    public DefaultTreeModel initCustomersTreeModel(Collection customers) {
        return new DefaultTreeModel(initCustomerTree(customers));
    }

    private DefaultMutableTreeNode initCustomerTree(Collection customers) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("mes Customers");
        DefaultMutableTreeNode tnType1 = null;
        DefaultMutableTreeNode tnType2 = null;
        DefaultMutableTreeNode tnType3 = null;
        DefaultMutableTreeNode tnCustomer = null;

        tnType1 = new DefaultMutableTreeNode(
                "Inactive");
        root.add(tnType1);
        tnType2 = new DefaultMutableTreeNode(
                "Active");
        root.add(tnType2);

        tnType3 = new DefaultMutableTreeNode(
                "BlackList");
        root.add(tnType3);

        for (Customer customer : (Collection<Customer>) customers) {
            if (customer.getStatusCustomer() == 10) {
                tnType1.add(new DefaultMutableTreeNode(customer));
            }
            if (customer.getStatusCustomer() == 11) {
                tnType2.add(new DefaultMutableTreeNode(customer));
            }
            if (customer.getStatusCustomer() == 12) {
                tnType3.add(new DefaultMutableTreeNode(customer));
            }
        }
        return root;

    }

    public DefaultTableModel initCustomersTableModel(Collection customers) {
        return new DefaultTableModel(initVectorTableData(customers), initVectorColumnNamesTable());
    }

    private Vector initVectorTableData(Collection customers) {
        final String mname = "initVectorTableData";
        CustomerService serviceCustomer = new CustomerService();
        Vector rowDada = new Vector();
        for (Customer customer : (Collection<Customer>) customers) {
            Vector colData = null;
            colData = new Vector();
            colData.add(customer);
            rowDada.add(customer.getVector());
        }

        return rowDada;
    }

    private Vector initVectorColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("Customer");
        columnNames.add("lOGIN");
        columnNames.add("First Name");
        columnNames.add("Last Name");
        columnNames.add("Email");
        columnNames.add("Comment");
        columnNames.add("Status");
        return columnNames;
    }

    public JComboBox getjComboBoxBill() {
        return jComboBoxBill;
    }

    public JComboBox getjComboBoxShip() {
        return jComboBoxShip;
    }

    public DefaultComboBoxModel initStatusCustomersComboBoxModel(Collection statusCustomers) {
        return new DefaultComboBoxModel(initStatusCustomersVector(statusCustomers));
    }

    private Vector initStatusCustomersVector(Collection statusCustomers) {
        final String mname = "initStatusOrdersVector";
        Vector v = new Vector();
        v.addAll(statusCustomers);
        return v;
    }

    public Collection chargeComboBoxStatusCustomers() {
        CustomerService serviceCustomer = new CustomerService();
        Collection infoStatus = new ArrayList();
        try {
            infoStatus = serviceCustomer.findStatusCustomers();
        } catch (ObjectNotFoundException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
        statusCustomersVector.clear();
        statusCustomersVector.addAll(infoStatus);
        return infoStatus;

    }

    public void chargeComboBoxCustomers() {
        CustomerService serviceCustomer = new CustomerService();
        Collection customers = null;
        try {
            customers = serviceCustomer.findCustomers();
            jComboBoxCustomers.setModel(initAdressBillComboBoxModel(customers));
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
        customersVector.clear();
        customersVector.addAll(customers);

    }

    protected final transient String _cname = this.getClass().getName();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer;
    private javax.swing.JButton jButtonAdressBilling;
    private javax.swing.JButton jButtonAdressShipping;
    private javax.swing.JButton jButtonCreateAdressBill;
    private javax.swing.JButton jButtonCreateAdressShip;
    private javax.swing.JButton jButtonCreateCustomer;
    private javax.swing.JButton jButtonSearchCustomer;
    private javax.swing.JButton jButtonSendAdressBill;
    private javax.swing.JButton jButtonSendAdressShip;
    private javax.swing.JButton jButtonUpdateAdressBill;
    private javax.swing.JButton jButtonUpdateCustomer;
    private javax.swing.JButton jButtonUptateAdressShip;
    private javax.swing.JComboBox jComboBoxBill;
    private javax.swing.JComboBox jComboBoxCustomers;
    private javax.swing.JComboBox jComboBoxSearchCustomer;
    private javax.swing.JComboBox jComboBoxShip;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogAddAdressBill;
    private javax.swing.JDialog jDialogAddAdressShip;
    private javax.swing.JLabel jLabeNameReceiverAdressShipp1;
    private javax.swing.JLabel jLabeNameReceiverAdressShipp2;
    private javax.swing.JLabel jLabelCityBill1;
    private javax.swing.JLabel jLabelCityShipp1;
    private javax.swing.JLabel jLabelCityShipp2;
    private javax.swing.JLabel jLabelCompany1;
    private javax.swing.JLabel jLabelCountryBill1;
    private javax.swing.JLabel jLabelCountryShipp1;
    private javax.swing.JLabel jLabelCountryShipp2;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelIdAdressBill1;
    private javax.swing.JLabel jLabelIdAdressShipp1;
    private javax.swing.JLabel jLabelIdAdressShipp2;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JLabel jLabelNameReceiverAdressBill1;
    private javax.swing.JLabel jLabelNumStreetBill1;
    private javax.swing.JLabel jLabelNumStreetShipp1;
    private javax.swing.JLabel jLabelNumStreetShipp2;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelSearch1;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JLabel jLabelStreet2Bill1;
    private javax.swing.JLabel jLabelStreet2Shipp1;
    private javax.swing.JLabel jLabelStreet2Shipp2;
    private javax.swing.JLabel jLabelStreetBill1;
    private javax.swing.JLabel jLabelStreetShipp1;
    private javax.swing.JLabel jLabelStreetShipp2;
    private javax.swing.JLabel jLabelZipCodeBill1;
    private javax.swing.JLabel jLabelZipCodeShipp1;
    private javax.swing.JLabel jLabelZipCodeShipp2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAccounts;
    private javax.swing.JPanel jPanelAdress;
    private javax.swing.JPanel jPanelBillingAdress1;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelShippingAdress1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneTree1;
    private javax.swing.JTabbedPane jTabbedPaneManageAccount;
    private javax.swing.JTable jTableCustomers;
    private javax.swing.JTextField jTextCityBill1;
    private javax.swing.JTextField jTextCityShipp;
    private javax.swing.JTextField jTextCityShipp1;
    private javax.swing.JTextField jTextCompany;
    private javax.swing.JTextField jTextCountryBill1;
    private javax.swing.JTextField jTextCountryShipp;
    private javax.swing.JTextField jTextCountryShipp1;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFirstName;
    private javax.swing.JTextField jTextIdAdressBill1;
    private javax.swing.JTextField jTextIdAdressShipp;
    private javax.swing.JTextField jTextIdAdressShipp1;
    private javax.swing.JTextField jTextLastName;
    private javax.swing.JTextField jTextLogin;
    private javax.swing.JTextField jTextNameReceiverAdressBill1;
    private javax.swing.JTextField jTextNameReceiverAdressShipp;
    private javax.swing.JTextField jTextNameReceiverAdressShipp1;
    private javax.swing.JTextField jTextNumStreetBill1;
    private javax.swing.JTextField jTextNumStreetShipp;
    private javax.swing.JTextField jTextNumStreetShipp1;
    private javax.swing.JTextField jTextPassword;
    private javax.swing.JTextField jTextSearchCustomer;
    private javax.swing.JTextField jTextStreet2Bill1;
    private javax.swing.JTextField jTextStreet2Shipp;
    private javax.swing.JTextField jTextStreet2Shipp1;
    private javax.swing.JTextField jTextStreetBill1;
    private javax.swing.JTextField jTextStreetShipp;
    private javax.swing.JTextField jTextStreetShipp1;
    private javax.swing.JTextField jTextZipCodeBill1;
    private javax.swing.JTextField jTextZipCodeShipp;
    private javax.swing.JTextField jTextZipCodeShipp1;
    private javax.swing.JTree jTreeCustomers;
    // End of variables declaration//GEN-END:variables
}
