/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cdi.g3.client.ui.swing;

import com.cdi.g3.common.exception.CheckException;
import com.cdi.g3.common.exception.FinderException;
import com.cdi.g3.common.exception.ObjectNotFoundException;
import com.cdi.g3.common.logging.Trace;
import com.cdi.g3.server.domain.customers.Adress;
import com.cdi.g3.server.domain.customers.Customer;
import com.cdi.g3.server.domain.orders.Orders;
import com.cdi.g3.server.service.customers.AdressService;
import com.cdi.g3.server.service.customers.CustomerService;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Apotheas
 */
public class JPanelFormCustomers extends javax.swing.JPanel {
    
    //public class JPanelFormCustomers extends  JDesktopPane{
    CustomerService serviceCustomer = new CustomerService();
    DefaultTableModel myModelAdressShip = new DefaultTableModel();
    DefaultTableModel myModelAdressBill = new DefaultTableModel();
    DefaultTableModel myModelCustomers = new DefaultTableModel();
    Vector adressBillList = new Vector();
    Vector adressShipList = new Vector();
    Vector customersVector = new Vector();
    
    
    DateFormat df = new SimpleDateFormat("dd-MM-YYYY");

    public JDialog getjDialogAddAdressBill() {
        return jDialogAddAdressShip;
    }
    
    public DefaultTableModel getMyModelAdressBill() {
        return myModelAdressBill;
    }

    public JDialog getjDialogAddAdressShip() {
        return jDialogAddAdressBill;
    }
    
    
    
    
    /**
     * Creates new form Accounts
     */
    public JPanelFormCustomers() {
        initComponents(); 
        jTableCustomers1.setAutoCreateRowSorter(true);
        
        jPanelShippingAdress1.setVisible(false);
        jPanelBillingAdress1.setVisible(false);
        jTextIdAdressBill1.setEditable(true);
        jTextIdAdressShipp1.setEditable(true);
        jTextIdAdressBill1.setEditable(true);
        
//        jButtonCreateAdressShip.setVisible(false);
//        jButtonCreateAdressBill.setVisible(false);
        
        jTableCustomers1.setVisible(true);
        
//        jButton11.setVisible(false);
//        jButton21.setVisible(false);    
        
        jPanelCustomer.setVisible(false);
        
        
        jPanelShippingAdress1.setVisible(false);
        jPanelBillingAdress1.setVisible(false);
        chargeComboBoxCustomers ();
        jTableCustomers.setModel(initCustomersTableModel(customersVector));
        
        
        
        
//        jComboBoxCustomers.setSelectedIndex(-1);
//        jComboBoxShip.setModel(initComboAdressShipModel(adressShipList));
//        jComboBoxBill.setModel(initComboAdressBillModel(adressBillList));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAddAdressShip = new javax.swing.JDialog();
        jPanelShippingAdress1 = new javax.swing.JPanel();
        jLabeNameReceiverAdressShipp1 = new javax.swing.JLabel();
        jTextNameReceiverAdressShipp1 = new javax.swing.JTextField();
        jLabelStreetShipp1 = new javax.swing.JLabel();
        jLabelZipCodeShipp1 = new javax.swing.JLabel();
        jLabelCityShipp1 = new javax.swing.JLabel();
        jTextStreetShipp1 = new javax.swing.JTextField();
        jTextCityShipp1 = new javax.swing.JTextField();
        jTextZipCodeShipp1 = new javax.swing.JTextField();
        jTextNumStreetShipp1 = new javax.swing.JTextField();
        jLabelNumStreetShipp1 = new javax.swing.JLabel();
        jTextStreet2Shipp1 = new javax.swing.JTextField();
        jLabelStreet2Shipp1 = new javax.swing.JLabel();
        jTextCountryShipp1 = new javax.swing.JTextField();
        jLabelCountryShipp1 = new javax.swing.JLabel();
        jTextIdAdressShipp1 = new javax.swing.JTextField();
        jLabelIdAdressShipp1 = new javax.swing.JLabel();
        jButtonSendAdressShip = new javax.swing.JButton();
        jDialogAddAdressBill = new javax.swing.JDialog();
        jPanelBillingAdress1 = new javax.swing.JPanel();
        jLabelZipCodeBill1 = new javax.swing.JLabel();
        jTextCityBill1 = new javax.swing.JTextField();
        jLabelNameReceiverAdressBill1 = new javax.swing.JLabel();
        jTextIdAdressBill1 = new javax.swing.JTextField();
        jTextNameReceiverAdressBill1 = new javax.swing.JTextField();
        jTextZipCodeBill1 = new javax.swing.JTextField();
        jLabelStreetBill1 = new javax.swing.JLabel();
        jLabelIdAdressBill1 = new javax.swing.JLabel();
        jTextStreetBill1 = new javax.swing.JTextField();
        jLabelCityBill1 = new javax.swing.JLabel();
        jTextNumStreetBill1 = new javax.swing.JTextField();
        jLabelNumStreetBill1 = new javax.swing.JLabel();
        jTextCountryBill1 = new javax.swing.JTextField();
        jLabelCountryBill1 = new javax.swing.JLabel();
        jTextStreet2Bill1 = new javax.swing.JTextField();
        jLabelStreet2Bill1 = new javax.swing.JLabel();
        jButtonSendAdressBill = new javax.swing.JButton();
        jPanelAccounts = new javax.swing.JPanel();
        jTabbedPaneManageAccount = new javax.swing.JTabbedPane();
        jScrollPaneTree1 = new javax.swing.JScrollPane();
        jTreeCustomers = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomers1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCustomers = new javax.swing.JTable();
        jPanelCustomer = new javax.swing.JPanel();
        jComboBoxStatus1 = new javax.swing.JComboBox<String>();
        jLabelStatus1 = new javax.swing.JLabel();
        jTextPassword1 = new javax.swing.JTextField();
        jLabelPassword1 = new javax.swing.JLabel();
        jTextCompany1 = new javax.swing.JTextField();
        jLabelCompany1 = new javax.swing.JLabel();
        jTextEmail1 = new javax.swing.JTextField();
        jLabelLogin1 = new javax.swing.JLabel();
        jTextFirstName1 = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jTextLogin1 = new javax.swing.JTextField();
        jLabelFirstName1 = new javax.swing.JLabel();
        jTextLastName1 = new javax.swing.JTextField();
        jLabelLastName1 = new javax.swing.JLabel();
        jButtonSend = new javax.swing.JButton();
        jComboBoxShip1 = new javax.swing.JComboBox();
        jComboBoxBill1 = new javax.swing.JComboBox();
        jButtonAdressShipping1 = new javax.swing.JButton();
        jButtonAdressBilling1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxCustomers1 = new javax.swing.JComboBox();
        jComboBoxSearchCustomer1 = new javax.swing.JComboBox();
        jLabelSearch1 = new javax.swing.JLabel();
        jTextSearchCustomer1 = new javax.swing.JTextField();
        jButtonSearchCustomer1 = new javax.swing.JButton();
        AddCustomer1 = new javax.swing.JButton();

        jPanelShippingAdress1.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping adress"));

        jLabeNameReceiverAdressShipp1.setText("Last Name  :");

        jLabelStreetShipp1.setText("Street   :");

        jLabelZipCodeShipp1.setText("Zip Code  :");

        jLabelCityShipp1.setText("City  :");

        jTextZipCodeShipp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeShipp1ActionPerformed(evt);
            }
        });

        jLabelNumStreetShipp1.setText("Num Street   :");

        jLabelStreet2Shipp1.setText("Street2");

        jLabelCountryShipp1.setText("Country");

        jLabelIdAdressShipp1.setText("Id Adress Ship");

        jButtonSendAdressShip.setText("Send ");
        jButtonSendAdressShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendAdressShipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelShippingAdress1Layout = new javax.swing.GroupLayout(jPanelShippingAdress1);
        jPanelShippingAdress1.setLayout(jPanelShippingAdress1Layout);
        jPanelShippingAdress1Layout.setHorizontalGroup(
            jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabeNameReceiverAdressShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelNumStreetShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNumStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreetShipp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelZipCodeShipp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStreet2Shipp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextStreet2Shipp1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextZipCodeShipp1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCityShipp1)
                            .addComponent(jLabelCountryShipp1)
                            .addComponent(jLabelIdAdressShipp1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIdAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextCountryShipp1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addComponent(jTextCityShipp1))))
                    .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSendAdressShip))))
        );
        jPanelShippingAdress1Layout.setVerticalGroup(
            jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShippingAdress1Layout.createSequentialGroup()
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNameReceiverAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumStreetShipp1)
                    .addComponent(jTextNumStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStreetShipp1)
                    .addComponent(jTextStreetShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Shipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Shipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipCodeShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCityShipp1)
                    .addComponent(jTextCityShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelShippingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressShipp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressShipp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSendAdressShip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddAdressShipLayout = new javax.swing.GroupLayout(jDialogAddAdressShip.getContentPane());
        jDialogAddAdressShip.getContentPane().setLayout(jDialogAddAdressShipLayout);
        jDialogAddAdressShipLayout.setHorizontalGroup(
            jDialogAddAdressShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelShippingAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogAddAdressShipLayout.setVerticalGroup(
            jDialogAddAdressShipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelShippingAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelBillingAdress1.setBorder(javax.swing.BorderFactory.createTitledBorder("Billing adress"));

        jLabelZipCodeBill1.setText("Zip Code  :");

        jLabelNameReceiverAdressBill1.setText("Last Name  :");

        jTextZipCodeBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextZipCodeBill1ActionPerformed(evt);
            }
        });

        jLabelStreetBill1.setText("Street   :");

        jLabelIdAdressBill1.setText("Id Adress Bill");

        jLabelCityBill1.setText("City  :");

        jLabelNumStreetBill1.setText("Num Street   :");

        jLabelCountryBill1.setText("Country");

        jLabelStreet2Bill1.setText("Street2");

        jButtonSendAdressBill.setText("send");
        jButtonSendAdressBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendAdressBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBillingAdress1Layout = new javax.swing.GroupLayout(jPanelBillingAdress1);
        jPanelBillingAdress1.setLayout(jPanelBillingAdress1Layout);
        jPanelBillingAdress1Layout.setHorizontalGroup(
            jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNameReceiverAdressBill1)
                            .addComponent(jLabelNumStreetBill1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNumStreetBill1)
                            .addComponent(jTextNameReceiverAdressBill1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdAdressBill1)
                            .addComponent(jLabelCountryBill1)
                            .addComponent(jLabelCityBill1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCountryBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCityBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdAdressBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreetBill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelStreet2Bill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextStreet2Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSendAdressBill))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingAdress1Layout.createSequentialGroup()
                        .addComponent(jLabelZipCodeBill1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextZipCodeBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBillingAdress1Layout.setVerticalGroup(
            jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingAdress1Layout.createSequentialGroup()
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameReceiverAdressBill1)
                    .addComponent(jTextNameReceiverAdressBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextNumStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumStreetBill1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreetBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreetBill1))
                .addGap(9, 9, 9)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStreet2Bill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStreet2Bill1))
                .addGap(7, 7, 7)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextZipCodeBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelZipCodeBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCityBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCityBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCountryBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillingAdress1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdAdressBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdAdressBill1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSendAdressBill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAddAdressBillLayout = new javax.swing.GroupLayout(jDialogAddAdressBill.getContentPane());
        jDialogAddAdressBill.getContentPane().setLayout(jDialogAddAdressBillLayout);
        jDialogAddAdressBillLayout.setHorizontalGroup(
            jDialogAddAdressBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddAdressBillLayout.createSequentialGroup()
                .addComponent(jPanelBillingAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jDialogAddAdressBillLayout.setVerticalGroup(
            jDialogAddAdressBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddAdressBillLayout.createSequentialGroup()
                .addComponent(jPanelBillingAdress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());

        jTreeCustomers.setBorder(javax.swing.BorderFactory.createTitledBorder("Profils"));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Status");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Active");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("BlackListed");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTreeCustomers.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTreeCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeCustomersMouseClicked(evt);
            }
        });
        jScrollPaneTree1.setViewportView(jTreeCustomers);

        jTabbedPaneManageAccount.addTab("Consult", jScrollPaneTree1);

        jTableCustomers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCustomers1);

        jTabbedPaneManageAccount.addTab("Customers", jScrollPane1);

        jTableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCustomers);

        jPanelCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(153, 153, 255))); // NOI18N

        jComboBoxStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Inactive", "BlackList" }));
        jComboBoxStatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatus1ActionPerformed(evt);
            }
        });

        jLabelStatus1.setText("Status  :");

        jTextPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPassword1ActionPerformed(evt);
            }
        });

        jLabelPassword1.setText("Password  :");

        jTextCompany1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompany1ActionPerformed(evt);
            }
        });

        jLabelCompany1.setText("Company  : ");

        jTextEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmail1ActionPerformed(evt);
            }
        });

        jLabelLogin1.setText("Login  :");

        jLabelEmail1.setText("Email  :");

        jTextLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLogin1ActionPerformed(evt);
            }
        });

        jLabelFirstName1.setText("First name :");

        jLabelLastName1.setText("Last  name :");

        jButtonSend.setText("Create Customer");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jComboBoxShip1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxShip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShip1ActionPerformed(evt);
            }
        });

        jComboBoxBill1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBill1ActionPerformed(evt);
            }
        });

        jButtonAdressShipping1.setText("Add AdressChipping");
        jButtonAdressShipping1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdressShipping1ActionPerformed(evt);
            }
        });

        jButtonAdressBilling1.setText("Add AdressBilling");
        jButtonAdressBilling1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdressBilling1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addComponent(jLabelLastName1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCustomerLayout.createSequentialGroup()
                                .addComponent(jLabelLogin1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCustomerLayout.createSequentialGroup()
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstName1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                .addComponent(jLabelCompany1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextCompany1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabelStatus1)
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBoxStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelCustomerLayout.createSequentialGroup()
                                        .addComponent(jLabelPassword1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxShip1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxBill1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdressShipping1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(jButtonAdressBilling1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin1)
                    .addComponent(jLabelStatus1)
                    .addComponent(jComboBoxStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxShip1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdressShipping1))
                .addGap(20, 20, 20)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword1)
                    .addComponent(jTextFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail1)
                    .addComponent(jComboBoxBill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdressBilling1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCompany1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCompany1)
                    .addComponent(jTextLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFirstName1))
                .addGap(18, 18, 18)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName1)
                    .addComponent(jTextLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButtonSend))
        );

        jComboBoxCustomers1.setModel(initAdressBillComboBoxModel(customersVector));
        jComboBoxCustomers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxCustomers1MouseEntered(evt);
            }
        });
        jComboBoxCustomers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCustomers1ActionPerformed(evt);
            }
        });

        jComboBoxSearchCustomer1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pseudo", "Email" }));

        jLabelSearch1.setText("search by pseudo/email  :");

        jButtonSearchCustomer1.setText("search");
        jButtonSearchCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchCustomer1ActionPerformed(evt);
            }
        });

        AddCustomer1.setText("AddCustomer");
        AddCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxCustomers1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSearch1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxSearchCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextSearchCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearchCustomer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddCustomer1)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabelSearch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCustomers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSearchCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSearchCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSearchCustomer1)
                            .addComponent(AddCustomer1))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanelCustomer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPaneManageAccount.addTab("tab4", jDesktopPane1);

        javax.swing.GroupLayout jPanelAccountsLayout = new javax.swing.GroupLayout(jPanelAccounts);
        jPanelAccounts.setLayout(jPanelAccountsLayout);
        jPanelAccountsLayout.setHorizontalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addComponent(jTabbedPaneManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAccountsLayout.setVerticalGroup(
            jPanelAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccountsLayout.createSequentialGroup()
                .addComponent(jTabbedPaneManageAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );

        add(jPanelAccounts, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jTextZipCodeShipp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeShipp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeShipp1ActionPerformed

    private void jTextZipCodeBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextZipCodeBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextZipCodeBill1ActionPerformed

    private void jButtonSendAdressBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendAdressBillActionPerformed
     
       final String mname = "jButtonCreateActionPerformed";
        AdressService serviceAdress = new AdressService();
        Adress adressBlling = new Adress();
        try {
            // Asks if we want to remove the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create adressBlling "
                , "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            adressBlling.setNameReceiverAdress(jTextNameReceiverAdressBill1.getText());
            adressBlling.setNumAdress(jTextNumStreetBill1.getText());
            adressBlling.setNameStreetAdress(jTextStreetBill1.getText());
             adressBlling.setNameStreet2Adress(jTextStreet2Bill1.getText());
            adressBlling.setZipcodeAdress(jTextZipCodeBill1.getText());
            adressBlling.setCityAdress(jTextCityBill1.getText());
            adressBlling.setCountryAdress(jTextCountryBill1.getText());
            adressBlling.setCustomerBillAdress(new Customer(jTextLogin1.getText()));
            adressBlling = serviceAdress.createAdress(adressBlling);
            adressBillList.add(adressBlling);
            // Create the customer
            JOptionPane.showMessageDialog(this, "adressBlling number " + adressBlling.getId()
                + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);
            
//            jButtonCreateAdressShip1.setVisible(false);
            
            jComboBoxBill1.setModel(initAdressShipComboBoxModel(adressBillList));
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the adress service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

        
        
        
    }//GEN-LAST:event_jButtonSendAdressBillActionPerformed

    private void jButtonSendAdressShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendAdressShipActionPerformed
        final String mname = "jButtonCreateActionPerformed";
        AdressService serviceAdress = new AdressService();
        Adress adressShipping = new Adress();
        try {
            // Asks if we want to remove the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create adressShipping "
                + adressShipping.getId(), "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            adressShipping.setNameReceiverAdress(jTextNameReceiverAdressShipp1.getText());
            adressShipping.setNumAdress(jTextNumStreetShipp1.getText());
            adressShipping.setNameStreetAdress(jTextStreetShipp1.getText());
             adressShipping.setNameStreet2Adress(jTextStreet2Shipp1.getText());
            adressShipping.setZipcodeAdress(jTextZipCodeShipp1.getText());
            adressShipping.setCityAdress(jTextCityShipp1.getText());
            adressShipping.setCountryAdress(jTextCountryShipp1.getText());
            adressShipping.setCustomerShipAdress(new Customer(jTextLogin1.getText()));
            adressShipping = serviceAdress.createAdress(adressShipping);
            adressShipList.add(adressShipping);
            // Create the customer
            JOptionPane.showMessageDialog(this, "adressShipping number " + adressShipping.getId()
                + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);
            jComboBoxShip1.setModel(initAdressShipComboBoxModel(adressShipList));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }
        
        
        
    }//GEN-LAST:event_jButtonSendAdressShipActionPerformed

    private void jButtonAdressBilling1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdressBilling1ActionPerformed
        JDialog  jDialogAdAdressBill = getjDialogAddAdressBill();
        jDialogAddAdressBill.setVisible(true);
        jPanelBillingAdress1.setVisible(true);
    }//GEN-LAST:event_jButtonAdressBilling1ActionPerformed

    private void jButtonAdressShipping1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdressShipping1ActionPerformed
        JDialog  jDialogAddAdressShip = getjDialogAddAdressShip();
        jDialogAddAdressShip.setVisible(true);
        jPanelShippingAdress1.setVisible(true);
    }//GEN-LAST:event_jButtonAdressShipping1ActionPerformed

    private void jComboBoxBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBill1ActionPerformed

    private void jComboBoxShip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShip1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxShip1ActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        final String mname = "jButtonCreateActionPerformed";
        CustomerService serviceCustomer = new CustomerService();
        Customer customer = null;
        try {
            customer = new Customer(jTextLogin1.getText(), jTextFirstName1.getText(), jTextLastName1.getText(), jTextEmail1.getText(), jTextPassword1.getText());

            // Asks if we want to create the customer
            final int anwser = JOptionPane.showConfirmDialog(this, "Do you want to create customer "
                + customer.getId() + " " + customer.getLastNameCustomer(), "Delete", JOptionPane.YES_NO_OPTION);
            if (anwser == JOptionPane.NO_OPTION) {
                return;
            }
            customer = serviceCustomer.createCustomer(customer);
            JOptionPane.showMessageDialog(this, "Customer number " + customer.getId()
                + " is creaeted", "info message", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot access the customer service", "Error", JOptionPane.ERROR_MESSAGE);
            Trace.throwing(_cname, mname, e);
        }

    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jTextLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLogin1ActionPerformed

    private void jTextEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmail1ActionPerformed

    private void jTextCompany1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompany1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompany1ActionPerformed

    private void jTextPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPassword1ActionPerformed

    private void jComboBoxStatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatus1ActionPerformed

    private void jTreeCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeCustomersMouseClicked
        final String mname = "jTreeCustomersMouseClicked";
        CustomerService serviceCustomer = new CustomerService();
        try {
            Collection customers = serviceCustomer.findCustomers();
            jTreeCustomers.setModel(initCustomersTreeModel(customers));
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTreeCustomersMouseClicked

    private void jComboBoxCustomers1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxCustomers1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCustomers1MouseEntered

    private void jComboBoxCustomers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCustomers1ActionPerformed
       customersVector.clear();
        customersVector.add((Customer)jComboBoxCustomers1.getSelectedItem());
        jTableCustomers.setModel(initCustomersTableModel(customersVector));
    }//GEN-LAST:event_jComboBoxCustomers1ActionPerformed

    private void jButtonSearchCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchCustomer1ActionPerformed
       final String mname = "jButtonSearchOrdersActionPerformed";
        Vector vOrders = new Vector();
        Collection orders = new ArrayList();

        if (jComboBoxSearchCustomer1.getSelectedIndex() == 0) {

            Customer customer = null;
            try {
                customer = serviceCustomer.findCustomer(jTextSearchCustomer1.getText());//
                orders.add(customer);

            } catch (FinderException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CheckException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (jComboBoxSearchCustomer1.getSelectedIndex() == 1) {
            Customer customer = null;
            try {
                customer = serviceCustomer.findCustomerByNumEmail("Email", jTextSearchCustomer1.getText());//
                orders.add(customer);

            } catch (ObjectNotFoundException ex) {
                Logger.getLogger(JPanelFormOrders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        vOrders.addAll(orders);
        jTableCustomers.setModel(initCustomersTableModel(vOrders));
    }//GEN-LAST:event_jButtonSearchCustomer1ActionPerformed

    private void AddCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomer1ActionPerformed
     jPanelCustomer.setVisible(true);
        jComboBoxShip1.setModel(initAdressShipComboBoxModel(adressShipList));
        jComboBoxBill1.setModel(initAdressShipComboBoxModel(adressBillList));

    }//GEN-LAST:event_AddCustomer1ActionPerformed
   
    public void setChampsBillingAdress(Adress adress){
        jTextNameReceiverAdressBill1.setText(adress.getNameReceiverAdress());
        jTextNumStreetBill1.setText(adress.getNumAdress());
        jTextStreetBill1.setText(adress.getNameStreetAdress());
        jTextStreet2Bill1.setText(adress.getNameStreet2Adress());
        jTextZipCodeBill1.setText(adress.getZipcodeAdress());
        jTextCityBill1.setText(adress.getCityAdress());
        jTextCountryBill1.setText(adress.getCountryAdress());
        jTextCompany1.setText(adress.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressBill1.setText(adress.getId());
        
    }
    public void clearBillingAdress(){
        jTextNameReceiverAdressBill1.setText("");
        jTextNumStreetBill1.setText("");
        jTextStreetBill1.setText("");
        jTextStreet2Bill1.setText("");
        jTextZipCodeBill1.setText("");
        jTextCityBill1.setText("");
        jTextCountryBill1.setText("");
        jTextCompany1.setText("");
        jTextIdAdressBill1.setText("");
        
    }
    
     public void setChampsShippingAdress(Adress adress){
        jTextNameReceiverAdressShipp1.setText(adress.getNameReceiverAdress());
        jTextNumStreetShipp1.setText(adress.getNumAdress());
        jTextStreetShipp1.setText(adress.getNameStreetAdress());
         jTextStreet2Shipp1.setText(adress.getNameStreet2Adress());
        jTextZipCodeShipp1.setText(adress.getZipcodeAdress());
        jTextCityShipp1.setText(adress.getCityAdress());
        jTextCountryShipp1.setText(adress.getCountryAdress());
        jTextCompany1.setText(adress.getNameCompanyReceiverAdress().getNameCompany());
        jTextIdAdressShipp1.setText(adress.getId());
        
    }
    public void clearShippingAdress(){
        jTextNameReceiverAdressShipp1.setText("");
        jTextNumStreetShipp1.setText("");
        jTextStreetShipp1.setText("");
        jTextStreet2Bill1.setText("");
        jTextZipCodeShipp1.setText("");
        jTextCityShipp1.setText("");
        jTextCountryShipp1.setText("");
        jTextCompany1.setText("");
        jTextIdAdressShipp1.setText("");
        
    }
    
   
    
    public DefaultComboBoxModel initCustomersComboBoxModel(Collection customers) {
        return new DefaultComboBoxModel( initCustomersVector(customers) );
    }
    private Vector initCustomersVector(Collection customers) {
        final String mname = "initCustomersVector";
        Vector v = new Vector();
        v.addAll(customers);
        return v;
    }  
    
    
    public DefaultComboBoxModel initAdressShipComboBoxModel(Collection adressesChip) {
        return new DefaultComboBoxModel( initAdressShipVector(adressesChip) );
    }
    private Vector initAdressShipVector(Collection adressesChip) {
        final String mname = "initAdressChipVector";
        Vector v = new Vector();
        v.addAll(adressesChip);
        return v;
    }
    public DefaultComboBoxModel initAdressBillComboBoxModel(Collection adressesBill) {
        return new DefaultComboBoxModel( initAdressBillVector(adressesBill) );
    }
    private Vector initAdressBillVector(Collection adressesBill) {
        final String mname = "initAdressChipVector";
        Vector v = new Vector();
        v.addAll(adressesBill);
        return v;
    }
    
    
    
     public DefaultTreeModel initCustomersTreeModel(Collection customers) {
        return new DefaultTreeModel(initCustomerTree(customers));
    }

    private DefaultMutableTreeNode initCustomerTree(Collection  customers) {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("mes Customers");
            DefaultMutableTreeNode tnType1 = null;
            DefaultMutableTreeNode tnType2 = null;
            DefaultMutableTreeNode tnType3 = null;
            DefaultMutableTreeNode tnCustomer = null;
            
            tnType1 = new DefaultMutableTreeNode(
                    "Inactive");
            root.add(tnType1);
            tnType2 = new DefaultMutableTreeNode(
                    "Active");
            root.add(tnType2);

            tnType3 = new DefaultMutableTreeNode(
                    "BlackList");
            root.add(tnType3);
            
        for (Customer customer : (Collection <Customer>) customers) {                
                if(customer.getStatusCustomer() ==10){
                    tnType1.add(new DefaultMutableTreeNode(customer));
                }
                if(customer.getStatusCustomer() ==11){
                    tnType2.add(new DefaultMutableTreeNode(customer));
                }
                if(customer.getStatusCustomer() ==12){
                    tnType3.add(new DefaultMutableTreeNode(customer));
                }                
                }
        return root;

    }
    
    
    
    public DefaultTableModel initCustomersTableModel(Collection    customers) {
        return new DefaultTableModel(initVectorTableData(customers), initVectorColumnNamesTable());
    }
    
    
    private Vector initVectorTableData(Collection    customers) {
       final String mname = "initVectorTableData";
       CustomerService serviceCustomer = new CustomerService();
       Vector rowDada = new Vector();
            for (Customer customer : (Collection <Customer>) customers) {
               Vector colData = null;
                colData = new Vector();
                colData.add(customer);
                rowDada.add(customer.getVector());
            }
        
        return rowDada; 
    }

    private Vector initVectorColumnNamesTable() {
        Vector<String> columnNames = new Vector();
        columnNames.add("Customer");
        columnNames.add("lOGIN");
        columnNames.add("First Name");
        columnNames.add("Last Name");
        columnNames.add("Email");
        columnNames.add("Comment");
        columnNames.add("Status");
        return columnNames;
    }

    public JComboBox getjComboBoxBill() {
        return jComboBoxBill1;
    }

    public JComboBox getjComboBoxShip() {
        return jComboBoxShip1;
    }
    
    
    public void chargeComboBoxCustomers (){
        CustomerService serviceCustomer = new CustomerService();
        Collection customers =null;
        try {
           customers = serviceCustomer.findCustomers();            
            jComboBoxCustomers1.setModel(initAdressBillComboBoxModel(customers));
        } catch (FinderException ex) {
            Logger.getLogger(JPanelFormCustomers.class.getName()).log(Level.SEVERE, null, ex);
        }
        customersVector.clear();
        customersVector.addAll(customers);
     
    }
    
    
    
    
    protected final transient String _cname = this.getClass().getName();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomer1;
    private javax.swing.JButton jButtonAdressBilling1;
    private javax.swing.JButton jButtonAdressShipping1;
    private javax.swing.JButton jButtonSearchCustomer1;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonSendAdressBill;
    private javax.swing.JButton jButtonSendAdressShip;
    private javax.swing.JComboBox jComboBoxBill1;
    private javax.swing.JComboBox jComboBoxCustomers1;
    private javax.swing.JComboBox jComboBoxSearchCustomer1;
    private javax.swing.JComboBox jComboBoxShip1;
    private javax.swing.JComboBox<String> jComboBoxStatus1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialogAddAdressBill;
    private javax.swing.JDialog jDialogAddAdressShip;
    private javax.swing.JLabel jLabeNameReceiverAdressShipp1;
    private javax.swing.JLabel jLabelCityBill1;
    private javax.swing.JLabel jLabelCityShipp1;
    private javax.swing.JLabel jLabelCompany1;
    private javax.swing.JLabel jLabelCountryBill1;
    private javax.swing.JLabel jLabelCountryShipp1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelIdAdressBill1;
    private javax.swing.JLabel jLabelIdAdressShipp1;
    private javax.swing.JLabel jLabelLastName1;
    private javax.swing.JLabel jLabelLogin1;
    private javax.swing.JLabel jLabelNameReceiverAdressBill1;
    private javax.swing.JLabel jLabelNumStreetBill1;
    private javax.swing.JLabel jLabelNumStreetShipp1;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelSearch1;
    private javax.swing.JLabel jLabelStatus1;
    private javax.swing.JLabel jLabelStreet2Bill1;
    private javax.swing.JLabel jLabelStreet2Shipp1;
    private javax.swing.JLabel jLabelStreetBill1;
    private javax.swing.JLabel jLabelStreetShipp1;
    private javax.swing.JLabel jLabelZipCodeBill1;
    private javax.swing.JLabel jLabelZipCodeShipp1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAccounts;
    private javax.swing.JPanel jPanelBillingAdress1;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelShippingAdress1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneTree1;
    private javax.swing.JTabbedPane jTabbedPaneManageAccount;
    private javax.swing.JTable jTableCustomers;
    private javax.swing.JTable jTableCustomers1;
    private javax.swing.JTextField jTextCityBill1;
    private javax.swing.JTextField jTextCityShipp1;
    private javax.swing.JTextField jTextCompany1;
    private javax.swing.JTextField jTextCountryBill1;
    private javax.swing.JTextField jTextCountryShipp1;
    private javax.swing.JTextField jTextEmail1;
    private javax.swing.JTextField jTextFirstName1;
    private javax.swing.JTextField jTextIdAdressBill1;
    private javax.swing.JTextField jTextIdAdressShipp1;
    private javax.swing.JTextField jTextLastName1;
    private javax.swing.JTextField jTextLogin1;
    private javax.swing.JTextField jTextNameReceiverAdressBill1;
    private javax.swing.JTextField jTextNameReceiverAdressShipp1;
    private javax.swing.JTextField jTextNumStreetBill1;
    private javax.swing.JTextField jTextNumStreetShipp1;
    private javax.swing.JTextField jTextPassword1;
    private javax.swing.JTextField jTextSearchCustomer1;
    private javax.swing.JTextField jTextStreet2Bill1;
    private javax.swing.JTextField jTextStreet2Shipp1;
    private javax.swing.JTextField jTextStreetBill1;
    private javax.swing.JTextField jTextStreetShipp1;
    private javax.swing.JTextField jTextZipCodeBill1;
    private javax.swing.JTextField jTextZipCodeShipp1;
    private javax.swing.JTree jTreeCustomers;
    // End of variables declaration//GEN-END:variables
}
